### ISSUE TITLE
[Feature Request]: 能否让用户能配置去掉下载页面顶部的 “当前不是最新版本！”

### ISSUE THREAD

**Issue by softwind0214** [tryzealot/zealot#1054]
### 描述 | Description

![image](https://user-images.githubusercontent.com/2074435/220054422-379f541a-e5c1-4b5e-9116-78e8b2e5e1c4.png)

就这个。能否提供一个配置可以让它去掉？

**Comment by icyleaf** [comment]
是需要一个全局的配置吗？

**Comment by icyleaf** [comment]
4.7.0 版本已发布
