### ISSUE TITLE
[Bug]: /api/apps/version_exist Cannot use t(".not_found") shortcut because path is not available

### ISSUE THREAD

**Issue by guyskk** [tryzealot/zealot#1148]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

cdn

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

当App版本不存在时，version_exist 接口异常，没有按文档返回404错误码。

请求示例，其中的版本号不存在：`/api/apps/version_exist?channel_key=xxxx&build_version=125&release_version=1.2.5&bundle_id=xxxx`

### 问题日志 | Relevant log output

```shell
method=GET path=/api/apps/version_exist format=html controller=Api::Apps::VersionExistController action=show status=500 duration=3.76 view=0.00 db=0.85 time=2023-04-27 04:28:22 +0800 exception=["RuntimeError", "Cannot use t(\".not_found\") shortcut because path is not available"] exception_object=Cannot use t(".not_found") shortcut because path is not available ip=xxxx token= channel_key=xxxx
```

**Comment by icyleaf** [comment]
谢谢反馈，问题已经修复版本，稍等 https://github.com/tryzealot/zealot/actions/runs/4815381438 构建完毕重新拉取 `nightly`

**Comment by guyskk** [comment]
已解决👍
