### ISSUE TITLE
[Feature Request]: iOS开发者添加UDID增加自定义名称

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1183]
### 描述 | Description

现在用zealot添加的UDID名称都是随机码，能否在添加UDID的页面，增加一个名称的输入框。

**Comment by mlch911** [comment]
注册设备需要提供设备名称，当前是会自动生成规则如下：
              `Zealot-[设备型号]-[4位随机数]`

_Originally posted by @icyleaf in https://github.com/tryzealot/zealot/issues/723#issuecomment-1193509174_

**Comment by icyleaf** [comment]
收到🫡

**Comment by icyleaf** [comment]
已经支持，具体操作看 #1200 有问题重开
