### ISSUE TITLE
[Feature Request]: 上传IOS应用包不能自动解析应用LOGO，Android应用包可以。

### ISSUE THREAD

**Issue by bilinxing** [tryzealot/zealot#1196]
### 描述 | Description

版本号
5.0.0-nightly
Git 哈希值
[7151359336000b6a2c4ba65ed38bffe2ffa78c0e](https://github.com/tryzealot/zealot/compare/5.0.0...7151359336000b6a2c4ba65ed38bffe2ffa78c0e)
构建日期
2023-07-01T15:17:44.182Z
操作系统
Linux 24e9e6f2a319 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64
Ruby 版本
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux-musl]

之前使用的同样是ruby开发的一个[应用分发项目](https://github.com/pluosi/app-host)，可以自动解析IOS和Android应用的LOGO， 请问是zealot是不支持IOS应用包的LOGO解析，还是我用的版本有bug么?

**Comment by icyleaf** [comment]
麻烦能告知 ipa 包里面 icon 的完整路径和文件名吗

**Comment by bilinxing** [comment]
> 麻烦能告知 ipa 包里面 icon 的完整路径和文件名吗

@icyleaf  根目录下:AppIcon-160x60@2x.png

**Comment by icyleaf** [comment]
Info.plist 文件是否有 `CFBundleIcons` 这个 Key 且其 value 是 `AppIcon-160x60@2x.png` 吗？

**Comment by icyleaf** [comment]
此问题无法复现，暂时关闭，有问题欢迎随时重新开启。

**Comment by bilinxing** [comment]
我们的IOS开发同事反馈CFBundleIcons是过时的配置，我翻阅[AppHost](https://github.com/pluosi/app-host/blob/703ed3952fc4d2e51bf0e6dade57309c3fb32efb/lib/parsers/pkg_adapter/ipa.rb#L25)的源码，发现他们是模糊匹配查找路径下的所有ICon图片文件，所以能够解析到。
`entry = zip_file.glob("Payload/*.app/#{app_icon_name}*x*0@*x.png").last`

**Comment by icyleaf** [comment]
恕我直言，这个逻辑我从 05 年一直用到现在，从[官方文档](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleicons?changes=latest_major&language=objc) 从来都没有标记过过时或废弃，现在任何 Xcode 创建的新项目也都会包含此 Key。

**Comment by bilinxing** [comment]
抱歉，由于我不是移动端开发，对技术细节不清楚，只能传话沟通。我们IOS开发同事反馈说APP是由多套ICON，采用https://cloud.tencent.com/developer/article/1972256 这篇文章中的【 新方案：在assets内新增图标项目】方式。

**Comment by icyleaf** [comment]
多谢反馈，我找到[对应的文档](https://developer.apple.com/documentation/xcode/configuring_your_app_to_use_alternate_app_icons)，确实是 iOS 15 之后的新特性，我会新开一个 PR 对此支持。

**Comment by icyleaf** [comment]
貌似找到问题了，通常 AppIcon 在打包会进行压缩处理，采用多 Icon 备用图标不会进行压缩，上传获取图标获取到解密后的文件为空造成的。

**Comment by bilinxing** [comment]
> 多谢反馈，我找到[对应的文档](https://developer.apple.com/documentation/xcode/configuring_your_app_to_use_alternate_app_icons)，确实是 iOS 15 之后的新特性，我会新开一个 PR 对此支持。
> 
> 按照官方教程，实际上它还建议在 CFBundleIcons 或 CFBundleIcons~ipad 支持 CFBundleAlternateIcons 的同时，设置 CFBundlePrimaryIcon 保证有一个主要的图标。如果有 CFBundlePrimaryIcon 是可以正常解析的出来的
> 
> <img alt="iShot_2023-07-19_10 55 43" width="423" src="https://user-images.githubusercontent.com/17814/254450619-6251339d-da4a-4cb7-9ebd-86ea63184f48.png">
> 麻烦把这些信息同步给 iOS 工程师，就可以解决当前的问题。

好的，多谢

**Comment by icyleaf** [comment]
使用 `nightly` tag 试试，如果之前也用的是请重新再拉取后部署

**Comment by bilinxing** [comment]
> 使用 `nightly` tag 试试，如果之前也用的是请重新再拉取后部署

升级到7月19日的最新nightly，IOS应用的图标可以正常解析了。效率真高👍 再次感谢！
