### ISSUE TITLE
[Bug]: build_version 比较问题

### ISSUE THREAD

**Issue by denymz** [tryzealot/zealot#1218]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

stable

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

使用 /api/apps/latest 接口获取最新版本时出现问题。
具体如下：
渠道中应用最新版本为 1.5.0，build_version 为 86；也只有这一个版本
当传递参数 release_version=1.5.0、build_version=86时，releases 返回为空。这没有问题。
当 build_version=85时，releases 返回了最新的一条记录，即1.5.0-86，这也没有问题。
但是，当build_version=87时，releases 也返回了最新的一条记录，即1.5.0-86。这是有问题的。
我猜想，当前的build_version应该只判断了是否相等。这种判断逻辑是否合理？

如果版本号相等的情况下，是否可以使用以下逻辑进行判断：
尝试解析build_version字段为数字后，比较大小。如果解析为数字时失败，则设为0，再进行判断。

总之，当release_version相同，build_version不同时，而直接返回最新版本的逻辑并不合理。

**Comment by icyleaf** [comment]
感谢反馈，这块的逻辑已经变更了好几次以兼容各种版本规则，问题已经修复，等待最新 `nightly` 构建完成可以解决。

**Comment by icyleaf** [comment]
有问题再开 :D
