### ISSUE TITLE
应用解包, 希望支持查看设备数以及 UDID

### ISSUE THREAD

**Issue by HolmesZhao** [tryzealot/zealot#1302]
### 描述 | Description

希望和蒲公英那些平台一样可以看到当前的描述文件(mobileprofile)中包含的设备数量和对应的 udid 

![image](https://github.com/tryzealot/zealot/assets/19728934/28049601-9cdc-4643-81da-e6dab8fd2074)

**Comment by icyleaf** [comment]
如果上传的 IPA 是 Ad Hoc 的包会在版本详情看到测试设备的

**Comment by icyleaf** [comment]
~~如果上传的 IPA 是 Ad Hoc 的包会在版本详情看到测试设备的。还是说只是希望在应用解包这个功能看到这个功能？~~

这俩功能其实都有，这实际上是一个 bug :D

**Comment by icyleaf** [comment]
等待 https://github.com/tryzealot/zealot/actions/runs/6477188938 完成后，重新拉取 `nightly` 后部署即可。

**Comment by HolmesZhao** [comment]
> 有，这实际上是一个 bug :D

好的~等待修复
