### ISSUE TITLE
[Bug]: iOS13上不显示安装按钮

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1335]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.0.0-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

e361f189444bcf491ff87eda2d14011020e3c417

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

iOS13设备访问网页，没有安装按钮
![image](https://github.com/tryzealot/zealot/assets/26565394/453f05a4-5a12-49f5-85d1-90f95882932f)

**Comment by icyleaf** [comment]
1. 什么设备
2. User Agent 是什么

**Comment by mlch911** [comment]
iphone se，ua我明天看看

**Comment by icyleaf** [comment]
顺便看看是不是浏览器禁用了 JavaScript，一般情况下只要是 iOS 设备都不会不展示的

**Comment by icyleaf** [comment]
8839cfdaa117ac53e7773af84f93b94bbd57ab29 解决了包名过长的问题

**Comment by mlch911** [comment]
UA `Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1`

**Comment by mlch911** [comment]
> 顺便看看是不是浏览器禁用了 JavaScript，一般情况下只要是 iOS 设备都不会不展示的

我看了设置里没有禁用

**Comment by icyleaf** [comment]
之前版本是正常的吗？我没有 SE 在模拟 UA 的环境下无法复现。

**Comment by mlch911** [comment]
我也不知道，第一次用这个老设备。

**Comment by icyleaf** [comment]
不确定是不是 js 编译的问题，微调了 728e7d0b09bf5607a98b1988ed41fe00ad5cb685 其他我也找不到具体哪里问题了

**Comment by icyleaf** [comment]
拉取最新版本 `nightly` 试试

**Comment by InjoyDeng** [comment]
我测试安装按钮在两个低版本 iOS 系统上的表现
--target=es2021 在 iOS 13 上不可见
--target=es2020 在 iOS 13 上可见
--target=es2018 在 iOS 10 上不可见
--target=es2017 在 iOS 10 上可见

**Comment by icyleaf** [comment]
感谢测试，保证最大的兼容度我改成 es2017 吧

**Comment by icyleaf** [comment]
fixed in 7dbb9ba8afdcd85e8f8c5b552c5b2a65fb5967b4

**Comment by mlch911** [comment]
测试了，没问题
