### ISSUE TITLE
上传iOS模拟器包的问题

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1343]
iOS模拟器的包，就是个后缀为`.app`的文件夹（相当于ipa文件解压后Payload里那个），通过网页是可以正常上传，上传后好像是会自动打成zip。

通过fastlane直接上传会报错，无法打开文件夹。
然后我手动zip后，上传zip还是会报错`应用无法正常解析，确保上传文件是支持的格式`

请问下模拟器包怎么通过fastlane上传？还是没有支持？
fastlane的命令如下
```ruby
zealot(
  endpoint: endpoint,
  token: lane_context[:ZEALOT_TOKEN],
  channel_key: channel_key,
  file: zip_app_path,
  changelog: git_log_markdown_text,
  hide_user_token: true,
  fail_on_error: false
)
```

_Originally posted by @mlch911 in https://github.com/tryzealot/zealot/discussions/1342_

**Comment by mlch911** [comment]
看了下文档和代码，两边的逻辑不一样，模拟器这个包匹配不到任何一种格式。能不能加一个手动上传的方法，手动传app_info的各种参数。

**Comment by icyleaf** [comment]
.app 是非标 ipa 格式不会特意支持。

如果需要你可以按照 ipa 的文件结构包一下压缩成 zip 后改名 ipa。

**Comment by mlch911** [comment]
能不能加一个手动上传的方法，手动传app_info的各种参数啊😅

**Comment by icyleaf** [comment]
> 能不能加一个手动上传的方法，手动传app_info的各种参数啊😅

没明白什么意思

**Comment by mlch911** [comment]
我这里打出来的包，只是ipa内的.app 目录，没有相关的metadata，所以这里一定失败，因为上传的包里根本没有对应的信息
https://github.com/tryzealot/zealot/blob/4649b492c05f865c65fd5329f74403df5233a153/app/controllers/api/apps/upload_controller.rb#L126

能否手动上传这里的对应参数，就不用去解析文件了？

**Comment by icyleaf** [comment]
文档写的有上传参数，详细的 metadata 是解析 app 获取的，接口并没有提供可以覆写的参数设置 https://zealot.ews.im/zh-Hans/docs/developer-guide/api/apps#%E4%B8%8A%E4%BC%A0%E5%BA%94%E7%94%A8

**Comment by mlch911** [comment]
问题就是我上传的.app包里没有 metadata 啊

**Comment by icyleaf** [comment]
不需要，解析也不是从 `iTunesMetadata.plist` 获取的，这个文件只有 appstore 下载的包才有

**Comment by mlch911** [comment]
将app包放到Payload文件夹内，然后zip，再改名为ipa，就上传成功了，感谢。
