### ISSUE TITLE
[Feature Request]:  更漂亮的分享页面

### ISSUE THREAD

**Issue by Avey777** [tryzealot/zealot#1356]
### 描述 | Description

![image](https://github.com/tryzealot/zealot/assets/35259040/6ec1e46c-6567-43b3-8c26-ec372e63995d)
现在的分享页面只有二维码， 可以增加一个单独的分享页面吗？ 像 [fir](http://fir.im/) 一样漂亮

**Comment by Avey777** [comment]
一些纯内部的应用， 还是希望直接使用这种单独的工具进行管理的。 但是分享页面有点粗糙，版本选择对于用户来说 还是有点繁琐 ， 希望可以重视这个问题

**Comment by icyleaf** [comment]
目前不太会做功能的大幅度修改，如果有特殊需求可以定制。
