### ISSUE TITLE
[Bug]: 上传adhoc ipa包失败 

### ISSUE THREAD

**Issue by techistoner** [tryzealot/zealot#1359]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.0.0-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

4649b492c05f865c65fd5329f74403df5233a153

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

![image](https://github.com/tryzealot/zealot/assets/5417557/61fa7a18-0b43-4817-93a9-10392d3a740b)

**Comment by icyleaf** [comment]
抱歉没有日志差不多问题

**Comment by techistoner** [comment]
我想问下，用了nginx做反向代理，带宽的话是阿里云的服务器也就5M的带宽，想要调整上传和下载的速度，是修改nginx配置么，修改了之后好像不起作用，是需要修改zealot的配置吗

**Comment by icyleaf** [comment]
你看下 nginx proxy_limit_rate 和 proxy_upload_rate 的配置

**Comment by icyleaf** [comment]
暂时关闭，有问题再开
