### ISSUE TITLE
[Bug]: 添加网络钩子报错

### ISSUE THREAD

**Issue by pianxian** [tryzealot/zealot#1381]
### 部署方式 | How to Deploy

源码部署 | Source

### 部署版本 | Version

5.1.0-nightly 

### Git 哈希值 (长度 40)| Git Ref (40 length)

0aff96d1acaf472706e529a80f1fd8872d9256c3

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

添加网络钩子报错 使用的是默认的模版
附图片如下
![WX20240104-190418@2x](https://github.com/tryzealot/zealot/assets/16642672/c063be64-f178-4084-8a56-1fcece27ada4)
![WX20240104-190546@2x](https://github.com/tryzealot/zealot/assets/16642672/1391f48a-2529-4ab6-9518-a0a0b4560e97)

**Comment by icyleaf** [comment]
无法复现也没收到匿名错误收集，还有其他错误日志信息吗？

**Comment by pianxian** [comment]
> 无法复现也没收到匿名错误收集，还有其他错误日志信息吗？

查找了log里没有这个事件 目前表现为json无法识别 从官网的企微JSON消息体样例复制的
![WX20240105-092853@2x](https://github.com/tryzealot/zealot/assets/16642672/89ac0f9e-8019-4bc8-912e-9485bf9579e4)

**Comment by icyleaf** [comment]
问题已找到，等待 [action](https://github.com/tryzealot/zealot/actions/runs/7417753088) 跑完重新拉取 tag 试试。

**Comment by pianxian** [comment]
> 问题已找到，等待 [action](https://github.com/tryzealot/zealot/actions/runs/7417753088) 跑完重新拉取 tag 试试。

![WX20240105-141559](https://github.com/tryzealot/zealot/assets/16642672/0b10a722-b13a-4cc3-8fa4-c2191d56250d)
![WX20240105-141615](https://github.com/tryzealot/zealot/assets/16642672/56c73337-f259-4869-81f2-580fef6a37b2)
更新了最新镜像还是报这个自定义消息体未知 JSON 格式

**Comment by icyleaf** [comment]
重新来取后重启服务了吗？

**Comment by icyleaf** [comment]
有问题重开，感谢反馈
