### ISSUE TITLE
[Feature Request]: Mac 的 UDID 添加

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1384]
### 描述 | Description

什么时候能支持下 mac 的 udid 添加

**Comment by icyleaf** [comment]
Mac 为什么还需要这个？

**Comment by mlch911** [comment]
> Mac 为什么还需要这个？

ios应用可以装在mac上的，用来测试很方便

**Comment by icyleaf** [comment]
需要等到节后再看这个问题了，目前没有开发环境。
