### ISSUE TITLE
[Feature Request]: 自動刪除舊的apk檔案。

### ISSUE THREAD

**Issue by maichanchinh** [tryzealot/zealot#1388]
### 描述 | Description

可以自動刪除舊的apk版本，避免資源浪費。
僅保存最多 5 個最近的 apk 版本，並刪除超過 30 天的 apk。

**Comment by icyleaf** [comment]
关联 ＃376

**Comment by icyleaf** [comment]
节后考虑加一个这样最多保留数的功能
