### ISSUE TITLE
[Bug]: 上传symbol 后，ios app 的下载页面报错“非常抱歉，服务当前遇到一些技术问题造成访问异常。”。exception_object=PG::UndefinedColumn: ERROR:  column "identifier" does not exist

### ISSUE THREAD

**Issue by dehengxu** [tryzealot/zealot#1406]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.1.0-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

1db5d6e53e7ed25ec5e59a033afe20c0698ab09c

### 反代服务 | Reverse Proxy

apisix

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

在后台先上传完debug ipa 后，接着上传对应的 symbol zip 文件，再回到对应包的版本页面时，提示 “非常抱歉，服务当前遇到一些技术问题造成访问异常。”。 后台日志如下:

exception_object=PG::UndefinedColumn: ERROR:  column "identifier" does not exist

但删除 symbol 之后，包下载页面就恢复正常了。

符号包里，有 app.dSYM 和 扩展 appex.dSYM 。

### 问题日志 | Relevant log output

```shell
method=GET path=/lPmui/35 format=html controller=ReleasesController action=show status=500 allocations=7674 duration=30.03 view=0.00 db=4.15 time=2024-02-22 18:05:24 +0800 exception=["ActionView::Template::Error", "PG::UndefinedColumn: ERROR:  column \"identifier\" does not exist\nLINE 1: ..._file_metadata\".\"debug_file_id\" = $1 AND (data -> identifier...\n                                                             ^\n"] exception_object=PG::UndefinedColumn: ERROR:  column "identifier" does not exist
zealot-zealot-1    | LINE 1: ..._file_metadata"."debug_file_id" = $1 AND (data -> identifier...
zealot-zealot-1    |                                                              ^

```
```

**Comment by icyleaf** [comment]
感谢反馈，请等待 [Action](https://github.com/tryzealot/zealot/actions/runs/8005734444) 成功包完后，重新拉取镜像、重启服务试试。

**Comment by dehengxu** [comment]
感谢你的回复 。我更新了最新镜像，上传 symbole 进度条到100%的时候，页面状态就保持不变了。
看起来没有进行后续的解析动作，日志也没有看到异常。

**Comment by icyleaf** [comment]
170MB 不算很大，会不会是上行带宽不太大。下次试试点击上传后留意下浏览器进度条，日志也应该会有提交 `POST /debug_file` 请求上传的日志和成功后的跳转日志，计算下提交到服务器实际的处理时间。

**Comment by dehengxu** [comment]
> 我本地测试一个 260+ MB 的多 dSYM 文件 zip 包上传也就不到 2 秒，上传应用还是调试文件的解析工作都是异步进行的不会卡在上传过程，能否新开一个 issue 并告知硬件配置和系统环境等信息

感谢，上传速度的问题，可能是网络原因。
