### ISSUE TITLE
[Bug][OIDC]: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by yiukamsum** [tryzealot/zealot#1461]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.2.2-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

2c9ed76beae9cd53811d9fb14c9345162c749df9

### 反代服务 | Reverse Proxy

cloudflare (== nginx)

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

我使用 OpenID Connect (Microsoft Azrue AD) 進行登入時，出現 500

### 问题日志 | Relevant log output

```shell
method=GET path=/users/auth/openid_connect/callback format=html controller=Users::OmniauthCallbacksController action=openid_connect status=500 allocations=1327 duration=62.54 view=0.00 db=0.44 time=2024-04-03 15:28:55 +0800 exception=["NoMethodError", "undefined method `+' for nil:NilClass"] exception_object=undefined method `+' for nil:NilClass ip=172.24.0.2 username=guest
```

**Comment by yiukamsum** [comment]
Just found out is the OIDC server returning nil for email. May be adding a error msg instead of returning 500?

**Comment by icyleaf** [comment]
Email address is actually not necessary for using the third party login account, I have revised this part of the logic so that the current problem will no longer occur.
