### ISSUE TITLE
[Bug]: 注册会报错「昵称不能为空值」

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1479]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.2.2-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

0cedc549b120dbc727b37fb0cba3653d60da3a20

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

注册会报错「昵称不能为空值」，昵称填啥都一样

### 问题日志 | Relevant log output

zealot.log
```shell
method=POST path=/users format=turbo_stream controller=Users::RegistrationsController action=create status=422 allocations=35203 duration=196.26 view=64.73 db=2.98 time=2024-04-29 12:00:13 +0800 ip=192.168.228.4 username=guest
```

**Comment by icyleaf** [comment]
最新的 5.2.3 和 nightly 都已经包含该修复
