### ISSUE TITLE
[Bug]: 苹果开发者添加失败

### ISSUE THREAD

**Issue by aliQWQ** [tryzealot/zealot#1484]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.1.0

### Git 哈希值 (长度 40)| Git Ref (40 length)

。

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

 *注册苹果开发者失败，填写信息后显示后台错误。* 
通过打印相关信息后发现，在appstoreconnect_api_role_permissions方法中，抛出了InvalidUserCredentialsError异常。
具体异常信息：
`Check errors(1) from response: 1. [401:NOT_AUTHORIZED] Authentication credentials are missing or invalid.: Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens`

原因猜测，苹果JWT令牌有20分钟的限时，可能是因为exp,iat设置错误导致？

> _已验证IId,KId,私钥的正确性_
> _已验证服务器时间设置_

**Comment by aliQWQ** [comment]
重试后已解决

**Comment by icyleaf** [comment]
如果是 API 超限会返回 429。从日志看返回 401 大概率是权限不足或传参错误造成的，重试的时候有对这个 issuer key 做权限调整吗？
