### ISSUE TITLE
[Feature Request]: 建议新增删除某个包的功能，能有多选最好

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1512]
### 描述 | Description

希望能选择某些包，然后一键删除。
显示的列表中也希望能够有过滤器，能够按「git分支」、「打包类型」、「上传来源」来过滤。

**Comment by mlch911** [comment]
另外，自动化删除任务，希望能支持按「git分支」等过滤后，来删除无用包

**Comment by icyleaf** [comment]
在应用渠道详情或版本详情右侧有主版本列表，点击进去的列表提供主版本号、打包类型、Git 分支的简单过滤。

多维度的复杂过滤我看看怎么实现

**Comment by mlch911** [comment]
> 在应用渠道详情或版本详情右侧有主版本列表，点击进去的列表提供主版本号、打包类型、Git 分支的简单过滤。
> 
> 多维度的复杂过滤我看看怎么实现

找到了，这个也能用。能加个多选删除和一键删除所有吗

**Comment by icyleaf** [comment]
功能已合并入 `nightly`

**Comment by icyleaf** [comment]
功能已合并，有问题再来

**Comment by mlch911** [comment]
@icyleaf 试了新功能，删除后会跳转到`versions`页面，应该停留在当前页面吧？

**Comment by icyleaf** [comment]
共用了同一删除方法忘记判断了 😆 9e8a7e8eb74e6d2ad9c980f07951fdc730f96f0d 已处理
