### ISSUE TITLE
[Bug]: 使用fastlane-plugin-zealot上传报错

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1516]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.2.3-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

5735c3d4bfbcaf43cf6fdd896d1e3b14fd4c633d

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

使用[fastlane-plugin-zealot](https://github.com/tryzealot/fastlane-plugin-zealot)上传报错
更新了一次版本后，就一直报错
```
Error uploading to Zealot [422]: {"error"=>"参数错误，请检查请求的参数是否正确", "entry"=>{"releases"=>["是无效的"]}}
```

代码
```
ENV['ZEALOT_ENDPOINT'] = 'url'
ENV['ZEALOT_TOKEN'] = 'xxx'
ENV['ZEALOT_HIDE_USER_TOKEN'] = 'true'
ENV['ZEALOT_FAIL_ON_ERROR'] = 'false'
zealot(
  channel_key:'xxx',
  changelog: 'xxx'
)
```

**Comment by icyleaf** [comment]
@rieset28 Would you pull the latest `nightly` or `nightly-2024-05-27` and deploy to test it again?

**Comment by mlch911** [comment]
> @rieset28 Would you pull the latest `nightly` or `nightly-2024-05-27` and deploy to test it again?

我刚更新的[e89c48e5ad9c49fde042170a115e000acb6b0818](https://github.com/tryzealot/zealot/compare/5.2.3...e89c48e5ad9c49fde042170a115e000acb6b0818)，试了还是不行
```
[!] Error uploading to Zealot [500]: {"error"=>"ERROR:  syntax error at or near \"WHERE\"\nLINE 1: UPDATE \"channels\" WHERE \"channels\".\"id\" = $1\n                          ^\n"}
```

**Comment by icyleaf** [comment]
The version 5.3.0 will be released ASAP.

**Comment by mlch911** [comment]
> > @rieset28 Would you pull the latest `nightly` or `nightly-2024-05-27` and deploy to test it again?
> 
> 我刚更新的[e89c48e5ad9c49fde042170a115e000acb6b0818](https://github.com/tryzealot/zealot/compare/5.2.3...e89c48e5ad9c49fde042170a115e000acb6b0818)，试了还是不行
> 
> ```
> [!] Error uploading to Zealot [500]: {"error"=>"ERROR:  syntax error at or near \"WHERE\"\nLINE 1: UPDATE \"channels\" WHERE \"channels\".\"id\" = $1\n                          ^\n"}
> ```

又更新了，现在没问题了。
