### ISSUE TITLE
[Bug]: iOS添加测试设备问题

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1542]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.3.0-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

b76e2c45d5f66691d6bbe546d3481c719addce38

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

测试设备同步，不会删除已被移除的设备，后续再添加该设备时，可以注册成功，但并没有真的添加该设备。

**Comment by icyleaf** [comment]
有问题再开
