### ISSUE TITLE
[Bug]: fastlane-plugin-zealot

### ISSUE THREAD

**Issue by rie-jos** [tryzealot/zealot#1557]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.3.2-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

2ddf401e6fdb335ce6ab3428da4d0e4e393aa182bfbf2836eecfdd584d9a9174

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

Hi,
using current version i get the following error, when i try to upload a file via zealot-fastlane-plugin with `password` parameter set.

`Error uploading to Zealot [422]: {"error"=>"Unprocessable entity", "entry"=>{"releases"=>["is invalid"]}}`

**Comment by icyleaf** [comment]
Confirmed.

**Comment by icyleaf** [comment]
Use `nightly-2024-06-24` to test it, thanks.

**Comment by icyleaf** [comment]
Release new version after #1558 was merged ASAP.

**Comment by icyleaf** [comment]
5.3.3 is out.
