### ISSUE TITLE
[Bug]: Incorrect Image URL on product-img

### ISSUE THREAD

**Issue by chlee1001** [tryzealot/zealot#1588]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.3.4

### Git 哈希值 (长度 40)| Git Ref (40 length)

2392236213644790ac6187ab639afbd444be99b5

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

There is an issue with the image URL being incorrectly input on the frontend:
```html
<div class="product-img"><img class="app-icon img-circle img-bordered-sm" data-release-id="2" data-channel-id="android_imhere_work" src="https://https://appcenter.lfin.kr//uploads/apps/a2/r2/icons/o-.png"></div>
```
`https://https://appcenter.lfin.kr//uploads/apps/a2/r2/icons/o-.png`
The URL contains ‘https://’ twice.

![image](https://github.com/user-attachments/assets/cf3cd6c1-961d-4a21-b665-9c232ffd61c6)

**Comment by icyleaf** [comment]
请检查设置 ZEALOT_DOMAIN 是否有 https，这里只需要设置域名，这里不需要有协议头

**Comment by chlee1001** [comment]
@icyleaf 

Thank you for your answer..
But ZEALOT_DOMAIN in my .env file is as follows

```
# Domain name, such as zealot.com, no need to add http:// or https:// prefix
ZEALOT_DOMAIN=appcenter.lfin.kr
```

**Comment by chlee1001** [comment]
Oh, I got it...
The DB settings table included https in the value of site_domain..

It's settled. Thank you
