### ISSUE TITLE
[Bug]: Member Role Unable to View Apps List When Guest Mode is Off

### ISSUE THREAD

**Issue by chlee1001** [tryzealot/zealot#1589]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.3.4

### Git 哈希值 (长度 40)| Git Ref (40 length)

2392236213644790ac6187ab639afbd444be99b5

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

自签名证书 Self-signed SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

I am experiencing an issue where users with the Member role cannot view the apps list when Guest Mode is turned off. According to the documentation on [this page](https://zealot.ews.im/docs/user-guide/administrator/permissions#roles), users with the Member role should be able to see all data, including the apps list.

Steps to Reproduce:

	1.	Set Guest Mode to Off.
	2.	Log in with an account that has Member role permissions.
	3.	Check if the apps list is visible.

Observed Behavior:

	•	When Guest Mode is Off, the apps list is not visible to users with the Member role.
	•	When Guest Mode is On, the apps list becomes visible not only to guests but also to users with the Member role.

Expected Behavior:

	•	With Guest Mode Off, users with the Member role should be able to view the apps list without any issues.

Could you please provide guidance on how to resolve this issue so that users with the Member role can see the apps list when Guest Mode is Off?

Thank you!

**Comment by icyleaf** [comment]
switch guest_mode needs restart service to apply. when the value was changed, restart button shows to let user restart or not.

**Comment by chlee1001** [comment]
@icyleaf 

If you enable guest mode and restart, both users with the member role and guest users can see the app. However, if you disable guest mode and restart, guest users will naturally see the login page, but users with the member role will not see the registered apps.

From what I know, users with the member role should be able to see the apps, right?

**Comment by icyleaf** [comment]
> From what I know, users with the member role should be able to see the apps, right?

Correct.

Sorry, I just understood what you meant. Members can see the application based on the fact that they are members within the application. This supplementary information was missing from the documentation.

**Comment by icyleaf** [comment]
indeed. Invite or user register first then add user to App's collaboration list.

**Comment by chlee1001** [comment]
@icyleaf 

Thanks for the quick response.

It would be great if there was a feature to create user groups and add those groups to collaborators. I’m planning to upload many apps and assign many users, similar to how it works in MS App Center.
