### ISSUE TITLE
[Bug]: 在Android微信里扫码打开应用，提示“点击右上角菜单 在safari中打开并安装”

### ISSUE THREAD

**Issue by GanHuaLin** [tryzealot/zealot#1593]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.3.4

### Git 哈希值 (长度 40)| Git Ref (40 length)

2392236213644790ac6187ab639afbd444be99b5

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

Android下应该显示在 浏览器 里打开并安装，而不是safari

**Comment by icyleaf** [comment]
关联 #1596
