### ISSUE TITLE
[Bug]: rack 升级后导致 LDAP 不能使用

### ISSUE THREAD

**Issue by InjoyDeng** [tryzealot/zealot#1613]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.3.1

### Git 哈希值 (长度 40)| Git Ref (40 length)

d1e9f5a669da400eaf3821bb8a7ee6219424fef5

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

经排查，是 6 月 19 号升级了 rack 后就出问题了
> d1e9f5a6 chore(deps): bump good_job from 3.29.3 to 3.29.4

gem 'rack', '3.0.11' 指定版本后问题解决。
水平有限，没有细究原因

**Comment by icyleaf** [comment]
关联 omniauth/omniauth#1135

**Comment by officebluesource** [comment]
no on my side :(

![grafik](https://github.com/user-attachments/assets/b9f7ecf3-65d5-423a-b18c-6f79cf44fb55)
