### ISSUE TITLE
[Bug]: OpenID Connect Button missing on login page

### ISSUE THREAD

**Issue by officebluesource** [tryzealot/zealot#1645]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.3.5 and 5.3.6

### Git 哈希值 (长度 40)| Git Ref (40 length)

dont know

### 反代服务 | Reverse Proxy

ngnix

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

Hi,
after update from 5.3.3 to 5.3.6 the button "Sign in with OpenID" is missing on the login page. 
5.3.5 has the same issue, 5.3.4 works

regards

**Comment by icyleaf** [comment]
Relates to #1613, and it had been fixed in 5.3.6. [demo](https://tryzealot.ews.im/users/sign_in) site works.

**Comment by officebluesource** [comment]
no in my side :(

![grafik](https://github.com/user-attachments/assets/b309322b-39ae-49f5-932d-aaa1979b058e)

**Comment by icyleaf** [comment]
Do you disable it either in Setting page or enviroment variable (`OIDC_ENABLED=false`)?

**Comment by officebluesource** [comment]
no, is enabled in both gui and the env-file
![grafik](https://github.com/user-attachments/assets/1d04aee9-52b9-4774-a6fb-2d1ccd1405e6)

![grafik](https://github.com/user-attachments/assets/27a46fb1-c32a-45f8-b876-cbc4f4dd1f80)

**Comment by icyleaf** [comment]
So wired, do you try restart the zealot service?

**Comment by icyleaf** [comment]
Sorry, I've checked all the possible locations and found no issues at all. Moreover, the version you've screenshotted above is the nightly version, which is the latest development version and does not have the issue you mentioned. Or is there any private communication method to help you find the specific problem?

**Comment by officebluesource** [comment]
thanks for your effort! I will try to create a new instance with a fresh postgres database. this will work

**Comment by officebluesource** [comment]
Hi @icyleaf 
I set up a test version 5.3.6 with an empty database today, and the OIDC login works without any issues. So it's either an issue with the upgrade/downgrade of Rack between the versions or some problem with the data in the Postgres database.
Is there any data related to OIDC stored in the database?

**Comment by icyleaf** [comment]
Thanks for testing feedback.

> Is there any data related to OIDC stored in the database?

It will store the OIDC setting if configure it from Setting page. dig the data from DB:

`SELECT FROM settings WHERE var = 'oidc'`

**Comment by officebluesource** [comment]
@icyleaf I just run through the whole upgrade process with an fresh test-instance (no data, just the initial setup database with `docker-compose run --rm zealot run_upgrade` )

starting with 5.3.0 -> 5.3.1 -> 5.3.2 -> 5.3.3 -> 5.3.4. Everything good, OIDC Button is there. 
then
upgrade to 5.3.5 -> OIDC Button gone -> upgrade 5.3.6 -> still missing

Fresh installation of 5.3.6 works, only upgrade vom 5.3.5 and earlier seems to be faulty.
Something is breaking in the upgrade process

**Comment by officebluesource** [comment]
true that! I can confirm this behaviour. When I set ZEALOT_REGISTER_ENABLED to true, the OIDC button appears.
Unfortunately, this is not a solution for us, as we don't want user registration. Maybe you can seperate this logic in one of the next versions :)

Thanks!

**Comment by icyleaf** [comment]
This issue has been reported by other users before. After careful consideration, I have decided to retract this logic and disable the built-in registration feature. This will not affect third-party authorization logins. I will supplement a complete RFC later.

**Comment by icyleaf** [comment]
Relates to #1671
