### ISSUE TITLE
[Bug]: 添加iPhone的UDID失败

### ISSUE THREAD

**Issue by mlch911** [tryzealot/zealot#1662]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.3.6-nightly

### Git 哈希值 (长度 40)| Git Ref (40 length)

fdca38fe726b3bade35bc2a4d5798443da11b6bd

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

点击注册按钮后，没有反应，日志里也没有任何报错

**Comment by icyleaf** [comment]
已经修复
