### ISSUE TITLE
获取设备UDID的按钮，在微信里无法正常使用

### ISSUE THREAD

**Issue by GanHuaLin** [tryzealot/zealot#1667]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

5.3.5

### Git 哈希值 (长度 40)| Git Ref (40 length)

e656621283b130446b80519fa6f91889bec912a6

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

获取设备UDID的页面，在微信里点击获取后下载的文件用不了。
可用检测下载微信环境里的话，提示在浏览器里打开。
还有就是获取步骤可用优化下增加图片说明，类似蒲公英那样的说明
![1727178064724](https://github.com/user-attachments/assets/d835327d-cc86-4a0f-b16c-27da74894fd8)

**Comment by icyleaf** [comment]
加图的优化说明太难了，我需要做明暗+多语言的图，以目前情况我需要做四套图...

**Comment by icyleaf** [comment]
拉取最新 `nightly` 分支试试看

**Comment by GanHuaLin** [comment]
@icyleaf 哪个版本才能用上这个功能？

**Comment by icyleaf** [comment]
上次发布没有把这个功能放进去 😂
