### ISSUE TITLE
[Feature Request]: Application unpacking supports Android architecture

### ISSUE THREAD

**Issue by rakuyoMo** [tryzealot/zealot#1735]
### 描述 | Description

An Android app may generate multiple apk installation packages at one time: universal, 64-bit or 32-bit. Therefore, the information of product version, build version, application name, and packaging type are consistent, and they belong to the same channel, but the architecture is different. (The same app store may upload multiple architecture apks at the same time)

Now when uploading apk, the architecture information will not be displayed when the application is unpacked, and the file name will not contain the corresponding information when downloaded, which will make it impossible to distinguish when actually using it.

In addition to displaying the architecture in the unpacking information, it is hoped that the architecture information can be added to the file name when downloading the apk. This is a very critical information for distinguishing which apk to use when publishing to the app store.

Hope to add this function, thank you very much!

**Comment by icyleaf** [comment]
Android cannot parse architectures or I have not been able to find where to obtain them; what is known so far is that they can be obtained at runtime layer.

**Comment by rakuyoMo** [comment]
So I hope you can reconsider this request: https://github.com/tryzealot/zealot/issues/1611, which can be used as a compromise solution at this stage.

CI can build names like "arm64-v8a_2024_11_07_18_24_1.22.1.apk", "universal_2024_11_07_10_32_1.22.0.apk", so that users can clearly know what architecture they are downloading.

Otherwise, at this stage, unless the architecture is used as a channel, it is difficult to distinguish the architecture of different apk files in one channel. And it feels inappropriate to use the architecture as a channel.

**Comment by rakuyoMo** [comment]
Or consider using `apt dump badging app.apk | grep 'native-code'` ?

**Comment by icyleaf** [comment]
aapt is closed source project. i need find other way to do it with pure code.

**Comment by rakuyoMo** [comment]
OK.

I just wanted to let you know that it is very, very important to allow users to distinguish the architecture of the apk directly from the filename of the downloaded file.

Looking forward to your implementation of this feature. Have a nice day.

**Comment by icyleaf** [comment]
And `aapt` only return native-code with native code, else it will return empty.

**Comment by TOT-JIN** [comment]
I need this feature too !
