### ISSUE TITLE
DRAFT: 版本保留功能修改草案

### ISSUE THREAD

**Issue by icyleaf** [tryzealot/zealot#376]
服务一直使用[老版本清理机制](https://zealot.ews.im/#/configuration?id=%e6%b8%85%e7%90%86%e8%80%81%e7%89%88%e6%9c%ac)在对外开放使用之后有些不太适应，主要因为：

- [无法控制](https://github.com/tryzealot/zealot/commit/37cfc99c6085648357aa5c312268b3f1121f9dcf)每个应用都严格遵守[版本号标准](https://semver.org/)
- 部分应用需要保留历史版本

从以上原因也不能看出市面现有的系统都会有一个是否设置保留最大上传版本的功能特性，但我一直认为这个是太不智能的一刀切的粗暴的解决方案，因此本服务一直用的是自己研发的一套清理机制。

从全局出发现有的清理机制需要改进或变更，可以考虑从如下角度调整：

1. 磁盘空间大小，超出的按照最早的删除
1. 应用证书失效情况（只适用于 iOS 太有局限性），过期的就最早的删除
1. 设置过期时间，超出的按照最早的删除

目的主要是避免最粗暴的方式来减少不必要的麻烦。若大家认为设置最大上传数量是非常有必要的请拿出足够的理由来说服我 :D

**Comment by EasierLu** [comment]
本地的电脑，不够直接加硬盘了，反正也只是内网用

**Comment by icyleaf** [comment]
有点凡尔赛的感觉了，哈哈哈哈

**Comment by icyleaf** [comment]
暂时先放弃，后续或许会支持 #632 对磁盘的压力会小很多，同时在提供一个可以快速清理包文件的方式吧
