### ISSUE TITLE
ios上传报错

### ISSUE THREAD

**Issue by mxq0923** [tryzealot/zealot#431]
web界面上传ipa会出现错误

I, [2021-04-30T10:38:43.046464 #325]  INFO -- : [ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368] Started POST "/channels/YRI5l/releases" for 172.20.0.1 at 2021-04-30 10:38:43 +0800
I, [2021-04-30T10:38:43.048098 #325]  INFO -- : [ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368] Processing by ReleasesController#create as HTML
I, [2021-04-30T10:38:43.048232 #325]  INFO -- : [ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368]   Parameters: {"authenticity_token"=>"LhXue8CNBys8GMZiHsAbt9EEZRcbRjj6l+Qy7mPxwQd7XR3/S5Phx/6qn3mHlO+rzoMaYVjb39P+ZMdAI7AJ+g==", "release"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x00007f501686a700 @tempfile=#<Tempfile:/tmp/RackMultipart20210430-325-1jrrbo.ipa>, @original_filename="TFHuiLianMS.ipa", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"release[file]\"; filename=\"TFHuiLianMS.ipa\"\r\nContent-Type: application/octet-stream\r\n">, "changelog"=>"", "release_type"=>"", "branch"=>"", "git_commit"=>"", "ci_url"=>""}, "commit"=>"上传应用", "channel_id"=>"YRI5l"}
I, [2021-04-30T10:38:44.227643 #325]  INFO -- : [ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368] Completed 500 Internal Server Error in 1179ms (ActiveRecord: 0.3ms | Allocations: 191411)
F, [2021-04-30T10:38:44.228230 #325] FATAL -- : [ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368]   
[ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368] Zlib::DataError (invalid stored block lengths):
[ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368]   
[ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368] app/models/release.rb:53:in `block in upload_file'
[ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368] app/models/release.rb:39:in `upload_file'
[ota] [e9dcff1a-a06b-487a-b2c9-638731c5f368] app/controllers/releases_controller.rb:27:in `create'

**Comment by icyleaf** [comment]
初步判断是解密 iOS 图标 png 出现的问题 `Zlib::DataError (invalid stored block lengths)`

**Comment by icyleaf** [comment]
@mxq0923 能否从 TFHuiLianMS.ipa 包文件（不是源文件）里面的 AppIcon 打个包发给我一下呢？ 我个人目前无法复现这个抱错，感谢了

**Comment by mxq0923** [comment]
解压ipa没找到AppIcon目录或者文件。问我们ios同学 ，图标在 Assets.car 里面 
[Assets.zip](https://github.com/tryzealot/zealot/files/6622109/Assets.zip)

**Comment by mxq0923** [comment]
好像要专门工具解压 https://github.com/steventroughtonsmith/cartool

**Comment by icyleaf** [comment]
理论上不应该没有呢，如果方便可否方便把 ipa 分享一份呢，我来确认下。Assets.car 确实会有一份没错，但正常来说根目录应该还会保留一份，这个是在 Info.plist 声明的

**Comment by icyleaf** [comment]
> 好像要专门工具解压 https://github.com/steventroughtonsmith/cartool

推荐使用这个：https://github.com/bartoszj/acextract  😄

**Comment by icyleaf** [comment]
顺便补充下 Assets.car 里面的图标都是未经过 png 加密的， 提供的这个文件对于我来说没有测试的作用

**Comment by mxq0923** [comment]
[appicon.zip](https://github.com/tryzealot/zealot/files/6628685/appicon.zip)
打出的包里面有这个文件，详见附件

**Comment by mxq0923** [comment]
如果还不行我再上传ipa

**Comment by icyleaf** [comment]
刚查明这些也是未加密的，抱歉还得麻烦提供下 ipa 感谢

**Comment by mxq0923** [comment]
ipa 我上传到云平台了。你查收下。过期的话我重新上传。您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/2d0414b1c5b546 或进入 cowtransfer.com 获取，在首页输入取件码：130455（24小时内有效）

**Comment by mxq0923** [comment]
上次上传的已经过期，我重新上传
您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/ce48189a94804a 或进入 cowtransfer.com 获取，在首页输入取件码：522583（24小时内有效）

**Comment by icyleaf** [comment]
感谢再次上传，已经下载到，代我分析下哈

**Comment by icyleaf** [comment]
初步判断还真是 app icon 没有做 png 加密处理而 app_info 获取的时候会强制开启解密，我看看如何判断，谢谢

**Comment by icyleaf** [comment]
@mxq0923 拉下最新的 nightly 镜像就应该没问题了。
