### ISSUE TITLE
ERROR: for zealot-zealot  Cannot create container for service zealot: unknown log opt 'max-size' for journald log driver

### ISSUE THREAD

**Issue by liyinchigithub** [tryzealot/zealot#482]
![image](https://user-images.githubusercontent.com/19643260/122250743-7ed68300-cefc-11eb-9478-8e0fd04e3ae3.png)

**Comment by icyleaf** [comment]
分别提供下 `docker version`  和  `docker-compose version` 的结果

**Comment by liyinchigithub** [comment]
感谢大佬回复
docker info
![image](https://user-images.githubusercontent.com/19643260/122524781-1fd35400-d04b-11eb-9e65-caaae4153c9a.png)

docker-compose version
![image](https://user-images.githubusercontent.com/19643260/122524832-2feb3380-d04b-11eb-9627-0234238561f1.png)

**Comment by icyleaf** [comment]
我昨天更新了 zealot-docker 库，你可以更新下重新执行下 `./deploy` 或者在生成好的 `docker-compose.yml` 做如下的变动：

```diff
x-defaults: &defaults
  restart: unless-stopped
  image: tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  environment:
    ZEALOT_REDIS_HOST: redis
    ZEALOT_POSTGRES_HOST: postgres
  volumes:
    - zealot-data:/app/public
    - ./log:/app/log
   healthcheck:
     test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
   logging:
+    driver: json-file
     options:
       max-size: "1g"
       max-file: "10"
       max-buffer-size: "4m"
       mode: non-blocking
```

原因是你的 docker 默认 logging driver 用的是 journald 但[正常默认应该是 json-file](https://docs.docker.com/config/containers/logging/configure/) 的。

**Comment by liyinchigithub** [comment]
你好，非常感谢你的解答，
我重新更新最新工程，出现新的这个报错，好像是数据类型问题
![image](https://user-images.githubusercontent.com/19643260/122787275-c045a480-d2e7-11eb-90a9-91905541d6fa.png)


ERROR: for zealot-zealot  Cannot create container for service zealot: json: cannot unmarshal number into Go value of type string

**Comment by icyleaf** [comment]
那你就把整个 logging 部分移除，再试试吧 

```diff
x-defaults: &defaults
  restart: unless-stopped
  image: tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  environment:
    ZEALOT_REDIS_HOST: redis
    ZEALOT_POSTGRES_HOST: postgres
  volumes:
    - zealot-data:/app/public
    - ./log:/app/log
   healthcheck:
     test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
-  logging:
-    driver: json-file
-     options:
-       max-size: "1g"
-       max-file: "10"
-       max-buffer-size: "4m"
-       mode: non-blocking
```
