### ISSUE TITLE
zealot-zealot 容器起不来

### ISSUE THREAD

**Issue by hurongyang** [tryzealot/zealot#487]
你好，我 ./deploy 使用 no ssl 模式，zealot-zealot 容器报错，请问下是什么原因呢

ERROR: for zealot-zealot  Cannot create container for service zealot: json: cannot unmarshal number into Go value of type string

ERROR: for zealot  Cannot create container for service zealot: json: cannot unmarshal number into Go value of type string
ERROR: Encountered errors while bringing up the project.

![image](https://user-images.githubusercontent.com/17896811/122899581-84a9e980-d37e-11eb-9fd7-f5075c8d0663.png)

**Comment by icyleaf** [comment]
试试 [482](https://github.com/tryzealot/zealot/issues/482#issuecomment-865145943) 的方法。报错是 docker 在反序列化是无法把 number 类型转到 string 类型但就是没说是哪个字段。

**Comment by hurongyang** [comment]
> 巧妙[482](https://github.com/tryzealot/zealot/issues/482#issuecomment-865145943)的方法。 报错是docker在反序列化是无法把数字类型说到字符串类型但就是没有是哪个字段。

好的我试试

**Comment by hurongyang** [comment]
去掉后可以了，非常感谢
