### ISSUE TITLE
可以用 omniauth-feishu 集成一下 Feishu 登陆

### ISSUE THREAD

**Issue by huacnlee** [tryzealot/zealot#498]

**Comment by icyleaf** [comment]
收到！排期安排上，哈哈哈

**Comment by icyleaf** [comment]
等 renny-ren/omniauth-feishu#3 被合并发布新版本后我在跟进吧 :D

**Comment by huacnlee** [comment]
https://github.com/ruby-china/homeland/blob/main/config/initializers/devise.rb#L3

参考一下，OmniAuth 可以在 rails-settings-cached 里面动态配置。

另外，我看你给 Setting 加了分组，于是我在 rails-settings-cached 2.7.0 里面新增了可以容易分组的方式

**Comment by icyleaf** [comment]
Omniauth 取值和认证逻辑这块一直想重新收拾下，这些有动力了。

**Comment by huacnlee** [comment]
ActionMailer 的动态配置，可以参考这个：

https://github.com/ruby-china/homeland/blob/main/app/mailers/application_mailer.rb#L19

这样就可以在服务启动以后，在 Setting 里面随时修改了

**Comment by icyleaf** [comment]
https://github.com/tryzealot/zealot/runs/3028731696 这个 action 跑完更新下 nightly 版本就可以尝鲜支持飞书了，下周应该会发一个新版本 :D

**Comment by icyleaf** [comment]
4.1.0 版本已发布

**Comment by huacnlee** [comment]
<img width="1205" alt="截屏2021-07-19 10 38 32" src="https://user-images.githubusercontent.com/5518/126094947-0157c4de-c19a-4dbf-ac00-2c4026199748.png">

飞书登陆不是直接进入的？点击登陆以后还是回到了登陆页面。

你做的方式不是直接可以用 OmniAuth 完成注册登陆，还需要绑定一个账号吗？

**Comment by icyleaf** [comment]
我这可以直接登录的呢，授权之后就近 dashboard 了，你拉下最新的版本？
<img width="1370" alt="feishu_logged_in" src="https://user-images.githubusercontent.com/17814/126102867-f53c7ce1-4a06-40b6-b1d1-2f8da6861add.png">
