### ISSUE TITLE
Channel 页面交互需要调整才好用

### ISSUE THREAD

**Issue by huacnlee** [tryzealot/zealot#510]
![IMG_3586](https://user-images.githubusercontent.com/5518/126093473-99b9f8c7-02f6-46fe-92b9-d8e8ec40d25d.PNG)

打包应该 iOS, Android 居多，用户场景应该在手机的布局下更多一些。

上图的场景，最新上传动态较多，原本在右侧的「应用类型」「渠道」被排到后面去了，往往安装完了才发现，类型 / 渠道没选择正确。

可以反过来排

**Comment by icyleaf** [comment]
我的理解可能看最近上传的场景会更多一些，不过确实选错的话再选的成本确实会高很多。如果把应用类型和渠道放到上面会造成上面固定占据的太大空间但实际上主要是看下面。可能需要一个折叠设计。

**Comment by huacnlee** [comment]
渠道类型，实际上设计一下，顶部两行可以排下，比如用下拉选择

**Comment by icyleaf** [comment]
可以先用 `nightly` tag 使用这个功能 :D
