### ISSUE TITLE
飞书登陆，如果遇到用户注册（但未确认邮箱），会无法登陆

### ISSUE THREAD

**Issue by huacnlee** [tryzealot/zealot#517]
https://github.com/tryzealot/zealot/issues/498#issuecomment-882189058

上次我说这个问题查到了，是：

- 第一次没飞书的时候，我注册过，但我们系统邮件一直没发出去，我一直没确认账号
- 然后开启了飞书登陆，飞书扫描登陆 callback 以后，没成功，去了注册页面
- 今天我们删除了未确认的账号，我再次飞书登陆，成功了

**Comment by icyleaf** [comment]
明白，现在不确定我能否复现，现在飞书授权一直不给我 email 的权限 :D

**Comment by huacnlee** [comment]
你接入一个其他的一样呀，比如 GitHub OmniAuth

**Comment by icyleaf** [comment]
复现了，之前的逻辑是没有发现已存在的用户会创建用户并[跳过邮件确认](https://github.com/tryzealot/zealot/blob/57eeb10f89a01ec990ea7d4bdbd28f5adfec9da8/app/models/concerns/user_omniauth.rb#L15)，万万没想到还有这个 case，我会补上。

**Comment by huacnlee** [comment]
Devise 有 email_required? 的方式，可以让 OmniAuth 的用户忽略邮箱

**Comment by icyleaf** [comment]
已搞定 :P
