### ISSUE TITLE
希望能加入更多平台类型 App 的支持

### ISSUE THREAD

**Issue by ohdarling** [tryzealot/zealot#518]
现在 Zealot 只支持 APK 和 IPA 的解析，希望能加入更多应用类型的支持，例如

1. macOS 应用程序，使用 Zip 打包，解析根目录中的 .app，可以解析出图标及 Info.plist
2. Windows 应用程序，使用 Zip 打包，可以解析 exe 文件的图标，名称可以采用 exe 的文件名

这样 Zealot 就可以作为一个全平台的 dailybuild 平台来使用了。

**Comment by icyleaf** [comment]
感谢反馈。

1. macOS 我应该可以解析但如果文件格式是 dmg 会麻烦很多
1. Windows 的话我不确定能够解析什么，如果仅仅是图标和名字的感觉有点上不了台面  :D

**Comment by ohdarling** [comment]
exe 其实也包含很多信息的，版本号、架构啥的应该都有了。

**Comment by icyleaf** [comment]
一些 pe 解析器：
- https://github.com/Tieske/pe-parser
- https://github.com/Anadian/executable-metadata

**Comment by icyleaf** [comment]
我在进行中的是先把底层解析库支持 macOS 目前已基本完成，等 icyleaf/app_info#34 合并后会对这里做上层支持。

**Comment by ohdarling** [comment]
赞，这个特性已经合并到 daily 分支了吗？

**Comment by icyleaf** [comment]
最近比较忙，这个项目属于 side project 争取本周内吧

**Comment by icyleaf** [comment]
话说 Windows PE 格式的解析好麻烦哦，好累 :D

**Comment by panbb2023** [comment]
加油

**Comment by icyleaf** [comment]
https://github.com/tryzealot/zealot/tree/feature/upload-app-without-process 已经在写了，目前处于基本可用，还没做完功能性检查。

**Comment by panbb2023** [comment]
已收到，谢谢







                       
原始邮件
                       
                     

发件人："icyleaf"< ***@***.*** &gt;;

发件时间：2023/3/10 15:22

收件人："tryzealot/zealot"< ***@***.*** &gt;;

抄送人："panbb2023"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [tryzealot/zealot] 希望能加入更多平台类型 App 的支持 (#518)




 
https://github.com/tryzealot/zealot/tree/feature/upload-app-without-process 已经在写了，目前处于基本可用，还没做完功能性检查。
 
&mdash;

**Comment by icyleaf** [comment]
吃螃蟹的人请用 `nightly` 有问题再开。
