### ISSUE TITLE
在 iPad 和 M1 Mac 上增加安装按钮

### ISSUE THREAD

**Issue by ohdarling** [tryzealot/zealot#519]
我看了代码在平台判断里，把对 Mac 平台的判断去掉了，只保留了 iPhone 相关的，但是实际使用过程中在 iPad 以及 M1 Mac 上又需要 OTA 安装，我们是通过自行修改代码实现的，希望考虑一下这块功能。

app/application_helper.rb
(source =~ /iPhone|iPad|Unversal|ios|iOS/i).present?
改成
(source =~ /iPhone|iPad|Unversal|ios|iOS|Mac OS X/i).present?

**Comment by icyleaf** [comment]
您说的对！因为长期没有 iPad 和 M1 也没考虑那块的需求，这样改的原因主要是新的 iPad User Agent 和桌面 macOS 采用一样的 UA 无法单纯侦测，目前只能通过 js 判断分辨率之类的方法来检测，加上 M1 也能装 ipa 之后这款展示的逻辑是需要更新一波。

**Comment by icyleaf** [comment]
但是[很久之前](https://github.com/tryzealot/zealot/blob/dea09afa0f553e6072670c61de9039e487a76b71/app/views/releases/body/_metadata.html.slim#L71)【安装】和【下载】俩按钮只要是 ios 的包都会显示的，已经不存在这个问题了呢

**Comment by ohdarling** [comment]
现在是判断 iOS 逻辑这个部分的代码，其实会同时判断 UA 和包类型，只有同时为 iOS 才会返回 iOS：

https://github.com/tryzealot/zealot/blob/develop/app/helpers/application_helper.rb#L114

而判断 UA 部分的代码不知道什么时候把 Macintosh 去掉了？

https://github.com/tryzealot/zealot/blob/develop/app/helpers/application_helper.rb#L100

**Comment by icyleaf** [comment]
没想到自己又套了一层逻辑，暂时改成判断是 iOS 设备或者是 ios 包就显示，`ios?` 方法是判断 iOS 设备的不方便加其他设备的逻辑。

**Comment by icyleaf** [comment]
可以使用 `nightly` tag 使用词功能，欢迎有问题继续反馈 :D
