### ISSUE TITLE
求助本地 Docker 中的图片和 CSS 不能加载

### ISSUE THREAD

**Issue by ReverseScale** [tryzealot/zealot#549]
![image](https://user-images.githubusercontent.com/13606492/129550135-1d711d35-b437-4adf-a8e7-df15ea8adfbf.png)

本地 Docker 部署的，http 发起的请求，看的目录中 public 下是有图片和 CSS 文件的，但是请求会 404，请问可能是什么原因，多谢帮助？

**Comment by icyleaf** [comment]
请回答如下问题：

1. 你使用的 tryzealot/zealot 源码编译部署的吗？
2. 你是要的是 tryzealot/zealot-docker 部署的吗，如果是麻烦给下 git commit sha 

不太确定你用的是哪个，需要直接解决问题的话可以通过在 `.env` 或 docker 环境变量设置：`RAILS_SERVE_STATIC_FILES=true` 解决，自 docker 镜像包含了 caddy 之后静态资源就交由它管理了。

**Comment by ReverseScale** [comment]
感谢支持，已经可以了哈，就是 `RAILS_SERVE_STATIC_FILES` 设置问题。
