### ISSUE TITLE
docker部署报错

### ISSUE THREAD

**Issue by EasierLu** [tryzealot/zealot#557]
initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted

chmod: /var/lib/postgresql/data: Operation not permitted

**Comment by icyleaf** [comment]
提供下 `docker-compose.yml` 文件内容

**Comment by EasierLu** [comment]
换了台机器然后部署好了，晚点会提供 docker-compose.yml
好像现在的web页面无法上传？包括demo里面的上传功能也是不行的会提示“非常抱歉，服务当前遇到一些技术问题造成访问异常。”

**Comment by EasierLu** [comment]
# Generated on Mon Aug 23 11:47:08 CST 2021
# USE SSL: false
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:5-alpine
    command: redis-server
    volumes:
      - zealot-redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:12-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "80:80"

volumes:
  zealot-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: Data/zealot/uploads
  zealot-backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: Data/zealot/backup
  zealot-redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: Data/redis
  zealot-postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: Data/postgres

**Comment by EasierLu** [comment]
[docker-compose.yml](https://github.com/tryzealot/zealot/files/7029029/docker-compose.txt)

**Comment by EasierLu** [comment]
然后现在发现是mac下docker部署没问题，windows下docker+wsl+Ubuntu-20.04LTS会有这个权限问题

**Comment by icyleaf** [comment]
请检查 `Data/postgres` 的权限问题，可以考虑把权限改为 `777`

**Comment by EasierLu** [comment]
经过测试在WSL环境下改权限没用，后面我修改了路径现在部署上了，但是现在下载很奇怪 第一次请求必定是打不开的，然后等页面响应完再刷新一次(或多次)才能下载的到，然后再就是直接拒绝连接了

**Comment by icyleaf** [comment]
因为服务是在 macOS 开发、Linux 及 Docker 环境部署并没有在 Windows 系统做个测试，因此这些问题可能不太好验证和解决。

**Comment by EasierLu** [comment]
@icyleaf  刚刚仔细看了下，是因为我没有配置证书然后那个下载按钮跳转的是一个https页面https://localhost/download/releases/1

**Comment by icyleaf** [comment]
哦哦，因为 iOS 仅接受 https 的下载，我在部署脚本再做强提醒吧，谢谢反馈

**Comment by easonlin-bdy** [comment]
# docker-compose.yml文件

# Generated on Wed Feb 12 03:11:22 AM UTC 2025
# USE SSL: self-signed
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: registry.cn-shenzhen.aliyuncs.com/cxok/lb:zealot
  depends_on:
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
  web:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/etc/caddy/certs:/etc/caddy/certs:ro
    env_file: .env
    environment:
      ACME_AGREE: "true"

volumes:
  zealot-uploads:
    external: true
  zealot-backup:
    external: true
  zealot-postgres:
    external: true
---------------------------------------------
# .env文件

######################################

# SMTP
SMTP_DOMAIN=zealot.com
SMTP_ADDRESS=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=you@gmail.com
SMTP_PASSWORD=your_app_password
SMTP_AUTH_METHOD=plain
SMTP_ENABLE_STARTTLS=true

# 邮件默认收发人
ACTION_MAILER_DEFAULT_FROM=notifiacation@zealot.com
ACTION_MAILER_DEFAULT_TO=no-reply@zealot.com

######################################
# 定时任务
######################################

# 保留所有上传应用，否则会定期清理上传的应用（调试文件除外）
# 清理规则参见：https://zealot.ews.im/#/configuration
# ZEALOT_KEEP_UPLOADS=true

######################################
# 统计
######################################

# Google Analytics 统计
GOOGLE_ANALYTICS_ID=

# 匿名错误上报
ZEALOT_SENTRY_DISABLE=false

######################################
# 开发使用变量 （非开发者请忽略下面）
######################################

# Docker Compose 项目名（建议保留不变）
COMPOSE_PROJECT_NAME=zealot

# 加密密钥，建议使用 openssl 或者 rails secret 生成
SECRET_KEY_BASE='kyi8m8iz4al1dpp9gkm90z1qu7exrrwfe02bmvcoghp7dcvh2s7u42y53i8z36vkjr9ye7gdynk7inktf0gcjl450pc7f4zrtqaf3uulq21m1qfhwbsavm1og2163kuu'

# Puma 外部控制 API
PUMA_CONTROL_URL=0.0.0.0:9293
PUMA_CONTROL_URL_TOKEN=zealot

# The database name will automatically get the Rails environment appended to it
# such as: zealot_development or zealot_production.
ZEALOT_POSTGRES_HOST=postgres
ZEALOT_POSTGRES_PORT=5432
ZEALOT_POSTGRES_USERNAME=postgres
ZEALOT_POSTGRES_PASSWORD=ze@l0t
ZEALOT_POSTGRES_DB_NAME=zealot

# Or use URL format
ZEALOT_DATABASE_URL=postgresql://zealot:ze%40l0t@postgres:5432/zealot?sslmode=disable
cxok@ubuntu:~$ sudo docker ps -a
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                      PORTS                                                                                         NAMES
eec202e6f5ad   registry.cn-shenzhen.aliyuncs.com/cxok/lb:zealot   "/init"                  18 minutes ago   Up 18 minutes (unhealthy)   80/tcp                                                                                        zealot_zealot_1
10ab28804f51   postgres:14-alpine                                 "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes (healthy)     5432/tcp                                                                                      zealot_postgres_1
6e560364cc6c   caddy:2-alpine                                     "caddy run --config …"   18 minutes ago   Up 18 minutes               0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 443/udp, 2019/tcp   zealot_web_1

---------------------------------------------------------
zealot_zealot 容器器报错日志：

I, [2025-02-12T18:30:09.354816 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:10.347021 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:11.374883 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:12.351953 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:13.355567 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.

**Comment by easonlin-bdy** [comment]
# docker-compose.yml文件

# Generated on Wed Feb 12 03:11:22 AM UTC 2025
# USE SSL: self-signed
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: registry.cn-shenzhen.aliyuncs.com/cxok/lb:zealot
  depends_on:
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
  web:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/etc/caddy/certs:/etc/caddy/certs:ro
    env_file: .env
    environment:
      ACME_AGREE: "true"

volumes:
  zealot-uploads:
    external: true
  zealot-backup:
    external: true
  zealot-postgres:
    external: true
---------------------------------------------
# .env文件

######################################

# SMTP
SMTP_DOMAIN=zealot.com
SMTP_ADDRESS=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=you@gmail.com
SMTP_PASSWORD=your_app_password
SMTP_AUTH_METHOD=plain
SMTP_ENABLE_STARTTLS=true

# 邮件默认收发人
ACTION_MAILER_DEFAULT_FROM=notifiacation@zealot.com
ACTION_MAILER_DEFAULT_TO=no-reply@zealot.com

######################################
# 定时任务
######################################

# 保留所有上传应用，否则会定期清理上传的应用（调试文件除外）
# 清理规则参见：https://zealot.ews.im/#/configuration
# ZEALOT_KEEP_UPLOADS=true

######################################
# 统计
######################################

# Google Analytics 统计
GOOGLE_ANALYTICS_ID=

# 匿名错误上报
ZEALOT_SENTRY_DISABLE=false

######################################
# 开发使用变量 （非开发者请忽略下面）
######################################

# Docker Compose 项目名（建议保留不变）
COMPOSE_PROJECT_NAME=zealot

# 加密密钥，建议使用 openssl 或者 rails secret 生成
SECRET_KEY_BASE='kyi8m8iz4al1dpp9gkm90z1qu7exrrwfe02bmvcoghp7dcvh2s7u42y53i8z36vkjr9ye7gdynk7inktf0gcjl450pc7f4zrtqaf3uulq21m1qfhwbsavm1og2163kuu'

# Puma 外部控制 API
PUMA_CONTROL_URL=0.0.0.0:9293
PUMA_CONTROL_URL_TOKEN=zealot

# The database name will automatically get the Rails environment appended to it
# such as: zealot_development or zealot_production.
ZEALOT_POSTGRES_HOST=postgres
ZEALOT_POSTGRES_PORT=5432
ZEALOT_POSTGRES_USERNAME=postgres
ZEALOT_POSTGRES_PASSWORD=ze@l0t
ZEALOT_POSTGRES_DB_NAME=zealot

# Or use URL format
ZEALOT_DATABASE_URL=postgresql://zealot:ze%40l0t@postgres:5432/zealot?sslmode=disable
cxok@ubuntu:~$ sudo docker ps -a
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                      PORTS                                                                                         NAMES
eec202e6f5ad   registry.cn-shenzhen.aliyuncs.com/cxok/lb:zealot   "/init"                  18 minutes ago   Up 18 minutes (unhealthy)   80/tcp                                                                                        zealot_zealot_1
10ab28804f51   postgres:14-alpine                                 "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes (healthy)     5432/tcp                                                                                      zealot_postgres_1
6e560364cc6c   caddy:2-alpine                                     "caddy run --config …"   18 minutes ago   Up 18 minutes               0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 443/udp, 2019/tcp   zealot_web_1

---------------------------------------------------------
zealot_zealot 容器器报错日志：

I, [2025-02-12T18:30:09.354816 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:10.347021 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:11.374883 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:12.351953 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
.
I, [2025-02-12T18:30:13.355567 #592]  INFO -- : health_check failed: We could not find your database: zealot. Available database configurations can be found in config/database.yml.

To resolve this error:

- Did you not create the database, or did you delete it? To create the database, run:

    bin/rails db:create

- Has the database name changed? Verify that config/database.yml contains the correct database name.
