### ISSUE TITLE
不支持 nginx 同一个域名通过不同 path 反向代理到不同服务

### ISSUE THREAD

**Issue by wujianguo** [tryzealot/zealot#599]
我有一个域名，后端多个服务，通过 path 来走不同的服务，如gitlab, zealot。目前重定向到登录页时没有带 nginx 配置的 对应 
 location。比如如下的配置，我可以通过 https://dev.example.com/gitlab 正常访问 gitlab，我也应该可以通过 https://dev.example.com/zealot 正常访问 zealot。

```
server_name dev.example.com;

	location /gitlab {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		# try_files $uri $uri/ =404;
		proxy_pass  http://127.0.0.1:8929;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header REMOTE-HOST $remote_addr;
	}

	location /zealot {
		proxy_pass http://127.0.0.1:8093/;
		proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header REMOTE-HOST $remote_addr;
       }
```

**Comment by icyleaf** [comment]
建议使用二级域名单独配置。你的这种情况我没有实践过抱歉

**Comment by wujianguo** [comment]
ok，我这边看有时间提个pr把这个支持了。

然后
https://zealot.ews.im/#/deployment?id=%e7%ba%af-zealot-%e6%9c%8d%e5%8a%a1
按这个文档配置到nginx反向代理，部分跳转有问题，从 https://xxx/apps 点击 演示应用 开发版，按理说应该跳转到 https://xxx/channels/Sj406，实际跳转到http://xxx:443/channels/Sj406。

**Comment by Cleam** [comment]
> ok，我这边看有时间提个pr把这个支持了。
> 
> 然后 https://zealot.ews.im/#/deployment?id=%e7%ba%af-zealot-%e6%9c%8d%e5%8a%a1 按这个文档配置到nginx反向代理，部分跳转有问题，从 https://xxx/apps 点击 演示应用 开发版，按理说应该跳转到 [https://xxx/channels/Sj406，实际跳转到](https://xxx/channels/Sj406%EF%BC%8C%E5%AE%9E%E9%99%85%E8%B7%B3%E8%BD%AC%E5%88%B0) [http://xxx:443/channels/Sj406。](http://xxx:443/channels/Sj406%E3%80%82)

我碰到了这个跳转[问题](https://github.com/tryzealot/zealot/issues/670)，请问这个要怎么解决？
