### ISSUE TITLE
能够接入更多的后端存储支持

### ISSUE THREAD

**Issue by incubator4** [tryzealot/zealot#632]
例如可以把storage做成S3存储，这样一方面对本地磁盘压力小很多，另一方面可以对zealot伸缩以支持更高并发的场景

**Comment by icyleaf** [comment]
收到！不过本身就是一个内网服务有必要高并发么，哈哈

**Comment by incubator4** [comment]
> 收到！不过本身就是一个内网服务有必要高并发么，哈哈

最近有空看了一下，发现carrierwave的fog可以支持s3等存储，感觉改一些配置就好了。 我ruby不是很懂，本地调的好像有一些问题

**Comment by icyleaf** [comment]
上传什么的都很容易支持，主要是还有配套的一系列文件解析的工作

**Comment by incubator4** [comment]
> 上传什么的都很容易支持，主要是还有配套的一系列文件解析的工作

是指目前的文件解析只限于本地的文件吗，逻辑上来说s3的对象也是可以读流的，我去看一下源码看看实现起来困不困难

**Comment by icyleaf** [comment]
同步下来也没啥问题，目前的问题是文件解析是基本同步+部分异步的操作，改成异地存储就需要把整体的处理流程全部改掉这个会涉及大量的变更包括数据库层面也要做变动

**Comment by kangfenmao** [comment]
确实有需要呀，服务器带宽费用还是挺高的

**Comment by icyleaf** [comment]
> 确实有需要呀，服务器带宽费用还是挺高的

把 uploads 和 backups 用其他云存储插件来替代就可以解决了，无论是 docker volume 插件还是基于 CSI 协议的 k8s, nomad 都能暂时解决你的问题。
