### ISSUE TITLE
APP下载的分享页面

### ISSUE THREAD

**Issue by lework** [tryzealot/zealot#651]
类似 http://fir.im/ 的下载分享页面

**Comment by icyleaf** [comment]
还真没有具体应用下载分享页，可以提供两种页面地址：

### 1 应用渠道详情页

`https://YOUR_ZEALOT_URL/channels/SLUG`

其实 `YOUR_ZEALOT_URL` 是 zealot 服务地址，`SLUG` 是你对应应用渠道的唯一地址。

### 2 上传的版本详情页

`https://YOUR_ZEALOT_URL/channels/SLUG/releases/ID`

其实 `YOUR_ZEALOT_URL` 是 zealot 服务地址，`SLUG` 是你对应应用渠道的唯一地址，`ID` 是上传的版本 ID，为空的时候会自动调整到最新版本，所以可以直接分享

`https://YOUR_ZEALOT_URL/channels/SLUG/releases`
