### ISSUE TITLE
Android应用 发送钩子 发送了iOS的安装连接

### ISSUE THREAD

**Issue by josercc** [tryzealot/zealot#701]
Win+ 测试版 Android
版本号:1.4.0(1644478260)
更新说明:
- 没有找到更新日志，可能的原因：

- 开发者很懒没有留下更新日志😂
- 有不可抗拒的因素造成日志丢失👽

安装地址:
itms-services://?action=download-manifest&url=https://zealot.port2.io/channels/win_test/releases/3/install

**Comment by icyleaf** [comment]
收到，我来排查

**Comment by icyleaf** [comment]
拉取最新 `nightly` tag 看看有没有解决问题

**Comment by josercc** [comment]
@icyleaf 升级完毕 启动 连接打不开了 一致卡死 是不是80端口冲突了？ 可以更换其他端口启动吗？

**Comment by josercc** [comment]
@icyleaf 你的演示应用也挂掉了 我看了日志 提示数据库zealot不存在 还有setting表不存在类似的 我试了重新装依然报错

**Comment by icyleaf** [comment]
演示应用挂掉的问题解决，谢谢反馈

**Comment by josercc** [comment]
> 演示应用挂掉的问题解决，谢谢反馈

我用最新版本启动报错一样问题吗？

**Comment by josercc** [comment]
> 再拉取最新 nightly tag 看看，代码层面的问题

👌

**Comment by josercc** [comment]
@icyleaf 重新安装
非常抱歉，服务当前遇到一些技术问题造成访问异常。 这个错误

**Comment by icyleaf** [comment]
从你的个人主页看到你也是一个开发者的同时还是一个付费知识的传播者，请问你这样反馈错误信息合适吗，如果还一直这样请自行解决，我爱莫能助！

**Comment by josercc** [comment]
我只是App开发者，我对于后端部署一无所知，你的如果收费我也会支持的呀，不知道你的话从何而来，反馈问题都不让了吗

**Comment by josercc** [comment]
@icyleaf 大佬 原来是我删除了Image不会自动pull 我手动pull更新之后就没问题 占用了大佬的时间。我很早就star了，最近想起来，部署了。Jenkins对接了zealot插件，部署替代了fir.im。更新也替代了fir.im的检测更新。昨天挂了，我删除Dcoker，删除Image，重新deploy还是不行 才提问题的。抱歉大佬，问题解决了。
