### ISSUE TITLE
fastlane zealot 上传失败

### ISSUE THREAD

**Issue by josercc** [tryzealot/zealot#702]
```shell
+-------------+-----------------------------------------------------------+
|                        [32mSummary for zealot 0.8.0[0m                         |
+-------------+-----------------------------------------------------------+
| channel_key | win_test                                                  |
| file        | /Users/king/Library/Caches/apk/app-profile-1644561694.apk |
| changelog   | 体验版本                                                  |
|             | - - 修复 endpoint 路径错误                                |
| branch      | origin/develop-支持zealot部署                             |
| git_commit  | ab6248ada4efb596d81c1d9ea01ff617c768ec78                  |
| source      | jenkins                                                   |
| ci_url      | http://127.0.0.1:8080/job/win+_android/189/               |
+-------------+-----------------------------------------------------------+
[14:42:29]: [32mUploading to [http://127.0.0.1:80](http://127.0.0.1/) ...[0m
[14:42:33]: [31mError uploading to Zealot [422]: [0m
```

**Comment by icyleaf** [comment]
fastlane 执行命令的时候追加 `--verbose` 然后把结果在发出来一下

**Comment by josercc** [comment]
fastlane firim file:/Users/king/Library/Caches/apk/app-profile-1644561436.apk changelog:测试版本 --verbose

输出结果

INFO [2022-02-11 15:08:55.06]: Uploading to http://127.0.0.1:80 ...
DEBUG [2022-02-11 15:08:58.93]: 
ERROR [2022-02-11 15:08:58.93]: Error uploading to Zealot [422]: 
INFO [2022-02-11 15:08:58.93]: Successfully generated documentation at path '/Users/king/.jenkins/workspace/win+_android/android/fastlane/README.md'

**Comment by josercc** [comment]
@icyleaf 还有一个表现 是当我使用域名 https://zealot.port2.io 时候 提示 413 Request Entity Too Large

**Comment by icyleaf** [comment]
> 413 Request Entity Too Large

服务你是不是前端没有加了一层反代，413 明显是设置了上传大小限制。

**Comment by josercc** [comment]
> > 413 Request Entity Too Large
> 
> 服务你是不是前端没有加了一层反代，413 明显是设置了上传大小限制。

我就用port2(https://www.port2.com)的服务将内网转外网

**Comment by icyleaf** [comment]
那就检查 port2 的设置，这个跟 zealot 无关

**Comment by josercc** [comment]
> 那就检查 port2 的设置，这个跟 zealot 无关

<img width="585" alt="image" src="https://user-images.githubusercontent.com/4713847/153554804-b83ff6dc-154f-4092-85f2-c2830c3f569a.png">

没有任何设置 用http://127.0.0.1:80也报错
