### ISSUE TITLE
生成的下载链接 https://app.winnwemedical.com/download/releases/5 打不开，直接ip是可以下载的

### ISSUE THREAD

**Issue by josercc** [tryzealot/zealot#711]
大佬 再次打扰你了。服务已经部署在服务器上面，
证书是我们公司自己正式证书

通过域名解析绑定的IP:port

通过域名上传的apk 点击下载链接无法下载 https://app.winnwemedical.com/download/releases/5 显示连接不存在
但是将域名直接替换为IP是可以下载的
没有用到Nginx转发

求大佬帮忙。还有一个测试条件 在本机搭建的ip的https ，点击下载可以直接下载的。

元宵节快乐

**Comment by icyleaf** [comment]
抱歉这个是运维层面的事情跟本服务没有什么关系，建议安装官方文档部署 https://zealot.ews.im/#/deployment?id=%e7%ba%af-zealot-%e6%9c%8d%e5%8a%a1

**Comment by josercc** [comment]
> 抱歉这个是运维层面的事情跟本服务没有什么关系，建议安装官方文档部署 https://zealot.ews.im/#/deployment?id=%e7%ba%af-zealot-%e6%9c%8d%e5%8a%a1

有一点疑惑，域名打开，就只有下载链接打不开，还有加载App图标请求，其他都正常

**Comment by icyleaf** [comment]
请仔细通读一遍文档，里面都有提到 https://zealot.ews.im/#/configuration?id=%e9%85%8d%e7%bd%ae%e5%9f%9f%e5%90%8d

**Comment by josercc** [comment]
> 请仔细通读一遍文档，里面都有提到 https://zealot.ews.im/#/configuration?id=%e9%85%8d%e7%bd%ae%e5%9f%9f%e5%90%8d

谢谢大佬 这个域名配置了 找到原因了 我在.env 配置域名证书为绝对路径了 现在放在/caddy/etc/caddy/certs/ 下面变量为证书名字可以了 万分感谢 搞了一周了
