### ISSUE TITLE
脚本部署，caddy无法启动，容器端口无法映射到宿主机。

### ISSUE THREAD

**Issue by Emptyh-2077** [tryzealot/zealot#717]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

caddy

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

按照部署文档进行的，环境没有问题，拿其他项目测试过，具体故障为caddy容器一直起不来，手动起有报错。然后其他服务端口无法正确映射到外面，检查了yml文件没有问题。是否是Let's Encrypt SSL 证书那里配置有问题呢？
![image](https://user-images.githubusercontent.com/58688087/155051891-89cd035a-daf2-482e-865d-13f218ef17fb.png)
![image](https://user-images.githubusercontent.com/58688087/155056082-7dc39996-a1fa-4e61-9f4a-afe7d052eb46.png)

**Comment by icyleaf** [comment]
看看 caddy 的日志报错是什么

```bash
# 在 zealot-docker 目录下执行
docker compose logs  web
```

**Comment by icyleaf** [comment]
已经找到问题，麻烦重新拉取下 `zealot-docker` 就可以解决，不拉取的话直接修改 `caddy/etc/caddy/Caddyfile` 文件把下面的变更做下修改  ：

```diff
-reverse_proxy @static zealot
+reverse_proxy zealot
```

**Comment by Emptyh-2077** [comment]
感谢，按照你说的操作caddy已经正常了，端口映射也出来了，但是现在访问443端口还是会出现证书错误，能否帮忙看一下是证书配置那里有问题吗？
![image](https://user-images.githubusercontent.com/58688087/155071262-a10ed721-3ac8-458c-9a8a-c773963b7769.png)
![image](https://user-images.githubusercontent.com/58688087/155071277-18e4e968-defb-42cd-8911-c9bd1528701b.png)

**Comment by icyleaf** [comment]
Caddy 使用 Let 默认走的是 [HTTP-01 验证](https://letsencrypt.org/zh-cn/docs/challenge-types/#http-01-%E9%AA%8C%E8%AF%81%E6%96%B9%E5%BC%8F/)方式，请确认配置的域名是可以被公网访问且被验证的到。

**Comment by Emptyh-2077** [comment]
那么请问一下caddy用的证书格式是怎么样的呢？我需要把我的证书上传到Caddy上面，看了caddy/etc/caddy/certs下面没有默认的证书文件。

**Comment by icyleaf** [comment]
https://caddyserver.com/docs/caddyfile/directives/tls

**Comment by Emptyh-2077** [comment]
打扰一下大佬，我们公司有一个自己内网使用的泛域名证书，打算使用自签名证书方案，然后现在是遇到证书配置问题了，文件名那里是直接输证书名就行了对吗，会自动检索？然后证书是放在caddy/etc/caddy/certs目录下吗？Caddyfile文件需要修改吗，certs目录下证书文件后缀格式有参考吗？

**Comment by icyleaf** [comment]
参考我上个评论给的链接，里面你问的问题都有答案
