### ISSUE TITLE
RFC: iOS 设备名称自注册和同步顺带支持团队管理

### ISSUE THREAD

**Issue by icyleaf** [tryzealot/zealot#723]
## 现状

托管的 AdHoc 的 iOS 应用会显示包含测试设备 UDID 列表，之前可通过 `zealot-sync-device` fastlane 插件利用 Apple 开发者账户和密码手动同步，问题是同步不及时就会影响查看测试包的开发或测试同学无法确认上传的包是否包含自己的设备，尤其是新入职或者采购新 iOS 设备的时候。

服务本身提供获取 iOS UDID 设备的功能同时在获取之后会告知是否有可以按照的应用这本身是一个非常有用的功能，假如没有注册能够提供一个注册设备的功能，同步 CICD 在构建 AdHoc 包的时候自动更新一次证书会非常有帮助。

另外一点 iOS 已经提供使用 AuthKey + AppStoreConnectAPI 官方 API 来管理应用和证书等，不再涉及密码和二次认证的麻烦事情。

## 原理

- AppStoreConnectAPI 的 Key 对应一个公司主体
  - 通过 Key 可以拿到 Certficate 信息间接获取唯一的公司主体
- 现有 Devices 表新增设备类型并关联上传 Key 的公司主体
- 利用 Key 的功能可以注册、更新 Devices 列表

## 功能实现

- [x] 抽离之前的 iOS App 机器人审核使用的 AppStoreConnectAPI 类 https://github.com/icyleaf/tiny_appstore_connect
- [x] 测试设备表扩容设备类型，网页可通过 UDID 识别设备类型（如果 API 可以拿到的话）
- [x] 新增团队管理 Team ID，应用可能会是多个 Team ID 组成的，允许注册设备选择自己要注册的 Team 
- [x] 获取 UDID 设备若没有发现可安装的应用提示是否进行注册操作
- [x] 后台可以管理 AppStoreConnect API 配置的 AuthKey、团队和测试设备相关界面

## 功能截图

苹果开发者管理界面
<img width="1161" alt="Apple Developer Manage UI" src="https://user-images.githubusercontent.com/17814/180692071-6bf37b91-c6a1-4203-baa3-f49a7ad3ffb3.png">

获取未注册 UDID 设备可进行注册操作
<img width="766" alt="Register Deivce to Apple Develoer" src="https://user-images.githubusercontent.com/17814/180692112-250fdc5e-fd50-4023-ae7f-a20d35091ba1.png">

**Comment by icyleaf** [comment]
官方 AppStoreConnect API 没有相关 API 可以拿到团队（Team ID）如果要实现必须暴力匹配或者全量同步设备才行。这个需求暂时降低优先级。

**Comment by icyleaf** [comment]
犯困的我居然还能冒发灵感，通过 ASC 的 `certfificates` 接口获取到的内容包含证书本身，解析后的信息可以拿到 Team ID 的值

**Comment by icyleaf** [comment]
注册设备需要提供设备名称，当前是会自动生成规则如下：

`Zealot-[设备型号]-[4位随机数]`

**Comment by icyleaf** [comment]
注册设备需要提供设备名称，当前是会自动生成规则如下：

`Zealot-[设备型号]-[4位随机数]`

**Comment by icyleaf** [comment]
跟随 2022-07-25 nightly 功能上线，测试一段时间稳定后发布正式版本

**Comment by ycy0430** [comment]
请问大佬，获取未注册 UDID 设备进行注册操作，点击按钮后没有反应，是怎么回事呢

**Comment by icyleaf** [comment]
> 请问大佬，获取未注册 UDID 设备进行注册操作，点击按钮后没有反应，是怎么回事呢

请点击[这里](https://github.com/tryzealot/zealot/issues/new?assignees=&labels=bug&template=bug_report.yaml&title=%5BBug%5D%3A+) 提交补充必要的信息

**Comment by icyleaf** [comment]
简体中文版文档已发布：

https://zealot.ews.im/zh-Hans/docs/user-guide/toolkits/fetch-udid
https://zealot.ews.im/zh-Hans/docs/user-guide/administrator/apple-team
