### ISSUE TITLE
页面统计分析样式错乱

### ISSUE THREAD

**Issue by Cleam** [tryzealot/zealot#769]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

latest

### 反代服务 | Reverse Proxy

nginx

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

页面统计分析样式错乱，不知能否解决，如下图：

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/4132185/167823555-8a52e325-ffbd-4b4d-9f31-bd8f2e310e06.png">

<img width="608" alt="image" src="https://user-images.githubusercontent.com/4132185/167823861-94cf251d-f8ee-4458-813c-8beebbb49701.png">

谢谢！

**Comment by Cleam** [comment]
数据库分析页面也是丢失样式的：

<img width="654" alt="image" src="https://user-images.githubusercontent.com/4132185/167824597-1604e99a-7866-4705-8357-22ce601fdf9e.png">

不过我目前没用到，只是反馈下问题。

**Comment by icyleaf** [comment]
谢谢反馈

**Comment by icyleaf** [comment]
目前我在任何部署方式都没有遇到此问题，暂时先关闭，如果后续还有发生可持续反馈。
