### ISSUE TITLE
获取设备ID时，https转为http访问，IOS无法下载安装

### ISSUE THREAD

**Issue by songge1209** [tryzealot/zealot#789]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

latest

### 反代服务 | Reverse Proxy

caddy

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 问题日志 | Relevant log output

```shell
IOS安装和获取设备ID，都由https转成http访问，导致无法安装。
```

**Comment by icyleaf** [comment]
暂不做 bug 处理，关联 #788 应该是同一问题

**Comment by songge1209** [comment]
好的，多谢！

**Comment by icyleaf** [comment]
试试拉取最新的 nightly tag

**Comment by songge1209** [comment]
拉取了，已经好了。辛苦！！
