### ISSUE TITLE
iOS Channel overview页面 不能访问

### ISSUE THREAD

**Issue by tasselsd** [tryzealot/zealot#795]
### 部署方式 | How to Deploy

Docker (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

nginx

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

创建一个iOS 渠道，然后访问它

https://my-zealot-domain/t0HgR/overview

页面渲染：
非常抱歉，服务当前遇到一些技术问题造成访问异常。

### 问题日志 | Relevant log output

```shell
method=GET path=/t0HgR/overview format=html controller=ChannelsController action=show status=500 duration=63.35 view=0.00 db=14.53 time=2022-06-20 16:54:11 +0800 exception=["ActionView::Template::Error", "No route matches {:action=>\"show\", :channel=>nil, :controller=>\"channels\"}, possible unmatched constraints: [:channel]\nDid you mean?  friendly_channel_overview_url"] exception_object=No route matches {:action=>"show", :channel=>nil, :controller=>"channels"}, possible unmatched constraints: [:channel]
Did you mean?  friendly_channel_overview_url ip=172.31.0.1 username=管理员
```

**Comment by icyleaf** [comment]
`https://my-zealot-domain/t0HgR` 可以打开吗？感觉像是应用渠道不存在造成的

**Comment by tasselsd** [comment]
> `https://my-zealot-domain/t0HgR` 可以打开吗？感觉像是应用渠道不存在造成的

`https://my-zealot-domain/t0HgR` 可以打开

**Comment by icyleaf** [comment]
麻烦可以在详细描述下创建时的选项是怎么勾选的，创建后依次点击哪里。

我一直复现不了你的问题，感谢

**Comment by icyleaf** [comment]
可以等 https://github.com/tryzealot/zealot/actions/runs/2533054116 跑完重新拉取并部署

**Comment by tasselsd** [comment]
可以了。
