### ISSUE TITLE
安卓渠道更新接口返回IOS安装地址

### ISSUE THREAD

**Issue by denymz** [tryzealot/zealot#813]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

kong-2.8.1

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

使用Android channel key 请求/api/apps/latest 接口，返回的数据中install_url字段为 itms-services://?action=download-manifest&url=https://xxxxxxx/channels/jHtQn/releases/4/install
完整返回如下：

> {
>     "app_name": "xxxx 产品版 Android",
>     "bundle_id": "*",
>     "git_url": null,
>     "app": {
>         "id": 2,
>         "name": "xxxx"
>     },
>     "scheme": {
>         "id": 4,
>         "name": "产品版"
>     },
>     "releases": [
>         {
>             "version": 2,
>             "app_name": "xxxx 产品版 Android",
>             "bundle_id": "com.xxxx.xxxx",
>             "release_version": "1.0.1",
>             "build_version": "2",
>             "source": "web",
>             "branch": "",
>             "git_commit": "",
>             "ci_url": "",
>             "size": 28493843,
>             "icon_url": "https://xxxxx/uploads/apps/a2/r4/icons/ic_launcher.png",
>             "install_url": "itms-services://?action=download-manifest&url=https://xxxxxx/channels/jHtQn/releases/4/install",
>             "changelog": [
>                 {
>                     "message": "修复Bug"
>                 }
>             ],
>             "text_changelog": "- 修复Bug"
>         }
>     ]
> }

并且能够确定的是在zealot后台中该渠道的设备类型为Android，渠道唯一地址 jHtQn 也是与之匹配。
而且只上传过Android安装包，从未上传过IOS的安装包。
总结下来唯一的问题就是install_url返回错误数据。

因为对Ruby不熟悉，所以只能猜测是此处未获取到device_type。
https://github.com/tryzealot/zealot/blob/aa8da705b2cd9da9eb3b2d3fb06b6dae81f9679e/app/models/release.rb#L148

**Comment by icyleaf** [comment]
问题找到了，感谢反馈。

**Comment by icyleaf** [comment]
等待 https://github.com/tryzealot/zealot/actions/runs/2702091739 执行成功后重新拉取 `nightly` 并部署
