### ISSUE TITLE
删除版本失败

### ISSUE THREAD

**Issue by denymz** [tryzealot/zealot#833]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

kong-2.8.1

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

应用版本删除失败，渠道类型：Android。
URL：https://localhost/channels/0o3DE/releases/24
删除的请求方法应该是DELETE，但实际使用GET进行请求，导致无法删除版本，后经过手动构造DELETE方法的请求成功删除版本。问题出在前端使用了错误的请求方法。

**Comment by icyleaf** [comment]
试试最新的 nightly ？
