### ISSUE TITLE
[Feature Request]: 网络钩子添加提交者模板变量

### ISSUE THREAD

**Issue by tasselsd** [tryzealot/zealot#934]
### 描述 | Description

https://github.com/tryzealot/zealot/blob/develop/app/jobs/app_web_hook_job.rb#L44

网络钩子自定义消息体渲染时的变量上下文添加版本提交者模板变量

**Comment by icyleaf** [comment]
你说的版本提交者是指当前这个版本上传者还是指 commit 的开发者呢？前者还比较容易添加，后者的话我只能把这次 changelog 新增一个 `Object` 包含各自字段。

**Comment by icyleaf** [comment]
是否满足需求？

**Comment by tasselsd** [comment]
> 是否满足需求？

满足的。`commit author`显示在`changlog`里就行了

**Comment by icyleaf** [comment]
目前只合并了 PR 的功能。拉取最新 `nightly` tag 可进行尝试。

**Comment by tasselsd** [comment]
> 目前只合并了 PR 的功能。拉取最新 `nightly` tag 可进行尝试。

好的
