### ISSUE TITLE
[Bug]: iPhone陌生设备扫码UDID，点击注册本设备按钮无反应

### ISSUE THREAD

**Issue by ycy0430** [tryzealot/zealot#935]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

自签名证书 Self-signed SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

大佬你好，前两天参照文档，用docker一键部署分别在自己测试的服务器，也让运维在公司服务器上部署了最新的4.5.1版本， 其他功能都正常，也能用已添加证书的iOS设备正常下载安装，看到最近更新了苹果开发者功能，在网站文档上没有看到相关介绍，在github上更新日志了解了一下，觉得 未添加进设备证书的设备扫码就能一键添加 这个功能很厉害，于是添加了开发者，测试设备同步能正常同步，但是陌生设备扫码点击 注册本设备 按钮没有反应。我自己搭的和运维搭的都是这样，麻烦大佬看看怎么回事。

**用未添加进证书的设备扫码：**
<img width="604" alt="iShot_2022-10-27_10 50 58" src="https://user-images.githubusercontent.com/35298277/198180981-65e2dff0-8d99-4b3c-88fa-31efe626b331.png">

**用添加进证书的设备扫码 正常显示证书：**
<img width="463" alt="iShot_2022-10-27_10 55 49" src="https://user-images.githubusercontent.com/35298277/198181034-e5d3e9ae-925b-4283-9fdb-d8bfc07c81b3.png">

**前端页面报错：**
<img width="998" alt="iShot_2022-10-27_10 23 11" src="https://user-images.githubusercontent.com/35298277/198178824-b237ceef-7676-4722-9c3d-2c77b6754bc8.png">

<img width="1359" alt="iShot_2022-10-27_10 45 10" src="https://user-images.githubusercontent.com/35298277/198178982-ac88054b-3602-4ac6-a9f3-56002e37e084.png">

**服务日志：**
`method=POST path=/udid/944168d1ed98baab04c3193bb58f552cf35e2b05/register format=turbo_stream controller=UdidController action=register status=500 duration=5.20 view=0.00 db=0.36 time=2022-10-27 10:38:01 +0800 exception=["NoMethodError", "undefined method `errors' for #"] exception_object=undefined method `errors' for # ip=172.xx.xx.5 username=管理员
`

**Comment by icyleaf** [comment]
收到，明天我来看看。

**Comment by icyleaf** [comment]
d8fc280aade74e6d490bdb3d7ef75626e8d825f1 应该修复了，使用最新 `nightly` tag 部署看看

**Comment by ycy0430** [comment]
![image](https://user-images.githubusercontent.com/35298277/198523380-060277d1-68f6-4015-b219-d41842b1cde3.png)
更新最新版本 证书安装失败了
`method=GET path=/udid/install format=html controller=UdidController action=install status=200 duration=4.20 view=0.92 db=0.00 time=2022-10-28 14:55:16 +0800 ip=172.18.0.4 username=口袋开发
method=GET path=/udid/install format=html controller=UdidController action=install status=200 duration=3.66 view=0.84 db=0.00 time=2022-10-28 14:55:16 +0800 ip=172.18.0.4 username=口袋开发
method=POST path=/udid/retrieve format=*/* controller=UdidController action=create status=302 duration=2.24 view=0.00 db=0.00 location=https://wycy.site/udid/00008020-00114C6814B8002E time=2022-10-28 14:55:40 +0800 ip=172.18.0.4 username=guest
method=GET path=/udid/00008020-00114C6814B8002E format=*/* controller=UdidController action=show status=200 duration=19.63 view=9.98 db=4.95 time=2022-10-28 14:55:41 +0800 ip=172.18.0.4 username=guest`

**Comment by icyleaf** [comment]
把 301 写成 302 了，[一会](https://github.com/tryzealot/zealot/actions/runs/3343518597)麻烦在重新部署下

**Comment by ycy0430** [comment]
已经添加成功了，但是不能安装应用。
还是说我理解错了？这个功能只是帮我们添加陌生设备到后台吗？ 然后还是需要去苹果后台下载最新的证书再打包上传，这个设备才能安装吗？

**Comment by icyleaf** [comment]
Ad-Hoc 类型的安装逻辑：

1. 获取设备 UDID
1. 注册 UDID 到 Apple Developer 
1. 添加 UDID 到 Ad-Hoc Profile
1. 下载新的 Profile 并使用它打包

Zealot 作为分发系统目前还只完成了前两步，第三步其实可以实现但还没做，最后一步是必须通过构建系统解决的，建议使用 fastlane 的 [match](https://docs.fastlane.tools/actions/match/) action 每次构建是传递 `force_for_new_devices: true` 来解决，但构建的时间会稍微慢一点，因为需要比对是否有新设备

**Comment by ycy0430** [comment]
明白了，多谢大佬

**Comment by icyleaf** [comment]
我会尽快补充这部分的文档，方便大家理解。

你的反馈对这个项目非常重要，后续有问题或建议欢迎反馈。
