### ISSUE TITLE
[Feature Request]: 能否支持 api 上传 symbol 文件

### ISSUE THREAD

**Issue by softwind0214** [tryzealot/zealot#957]
### 描述 | Description

每次都要手动上传，有点不方便，能否支持 api 上传 symbol 文件呢，这样可以集成到 CI/CD 流程里

**Comment by icyleaf** [comment]
https://zealot.ews.im/zh-Hans/docs/developer-guide/api/debug_files

**Comment by softwind0214** [comment]
原来这里还有个文档，打扰了哈哈
