### ISSUE TITLE
关于调试文件的版本号问题

### ISSUE THREAD

**Issue by softwind0214** [tryzealot/zealot#961]
### 描述 | Description

如果我的产物里二进制有多个（除了主bin之外还有好几个framework），会导致调试文件也有多个。这时候我上传所有的调试文件后，自动分析产生的版本号会变成目录下随机一个调试文件的版本号。

我试了下 api 里增加了版本号参数，发现 iOS 的调试文件好像不起作用。

也不影响使用，就是错的版本号看着不爽。

能否支持下这种情况下的版本号识别？

**Comment by icyleaf** [comment]
如果是 API 提交建议依次上传只绑定一个项目 dSYM，三方库可以考虑不传或单独上传。

如果你是使用 fastlane `zealot_debug_file` 可以直接指定 xcode scheme:

```ruby
zealot_debug_file(
    endpoint: 'http://localhost:3000',
    token: '...',
    channel_key: '...',
    platform: :ios,
+    xcode_scheme: 'AppName',
    verify_ssl: false
)
```

**Comment by softwind0214** [comment]
大佬，我们的产物里会有自己的 framework，所以会有多个自己的 dsym 文件。第三方的不传没事，但我们自己的还是需要传的。api 上传的方式能否支持传 xcode_scheme 呢？

**Comment by icyleaf** [comment]
Zealot 只接受单个 xcode scheme 解析，API 上传多个会读取第一个因此会造成错误得版本号和 UDID。fastlane插件是插件层做了单独处理。

当前的建议是把 dSYM 每个单独上传，调试文件现在的功能和承载还比较单一。你的情况我已经了解，我在想如何对这块的功能做更好的扩展和应用场景，麻烦可以把你们存储这些 dSYM 后续的场景方便说下嘛，如果不方便公开回复可以 email 或[电报](https://t.me/icyleaf)私下沟通

**Comment by softwind0214** [comment]
> Zealot 只接受单个 xcode scheme 解析，API 上传多个会读取第一个因此会造成错误得版本号和 UDID。fastlane插件是插件层做了单独处理。
> 
> 当前的建议是把 dSYM 每个单独上传，调试文件现在的功能和承载还比较单一。你的情况我已经了解，我在想如何对这块的功能做更好的扩展和应用场景，麻烦可以把你们存储这些 dSYM 后续的场景方便说下嘛，如果不方便公开回复可以 email 或[电报](https://t.me/icyleaf)私下沟通

大佬你好，我们村 dSYM 主要是为了留档，为方便以后查问题。其实现在储存都没有问题，就是版本号错误导致很难和 app 对应上。如果能在 app 下载页面加上 dSYM 的链接，那就更方便使用了

**Comment by icyleaf** [comment]
在应用和调试文件两者之间，我确实没有想好它俩应该是怎样一个对应关系，你有什么好的建议吗？

**Comment by softwind0214** [comment]
> 在应用和调试文件两者之间，我确实没有想好它俩应该是怎样一个对应关系，你有什么好的建议吗？

我的理解是，保存调试文件目的是为了今后有需要的时候下下来能马上使用。所以需求就是：1，能完整保存；2，能一一对应。现在 1 是没问题的，我上传一个打包好的 zip，系统能帮我完整存好。2 的问题在于版本号显示不对。

我建议可以遍历上传的 zip 文件中的所有 dSYM 文件，文件里有 plist 配置，从这些配置中取一个和 ipa 的 bundleId 一样的调试文件，把它的 bundle version 和 short version 显示出来，应该就能对应上了。

**Comment by icyleaf** [comment]
关联 #1124

**Comment by icyleaf** [comment]
需求已经合并，备份好数据库后再部署 `nightly`，注意降级的话需要还原老的数据库结构。

**Comment by softwind0214** [comment]
> 需求已经合并，备份好数据库后再部署 `nightly`，注意降级的话需要还原老的数据库结构。

好的，多谢大佬，我找个没人用的时候试试
