### ISSUE TITLE
[Feature Request]: docker可以增加一个arm架构的镜像吗？

### ISSUE THREAD

**Issue by Mabisi** [tryzealot/zealot#969]
### 描述 | Description

试着自己编译了一下，但是没有成功~

**Comment by icyleaf** [comment]
是否支持 arm 镜像取决于使用的依赖是否支持，经过我测试的是 amd64 和 Macbook M1 arm64 芯片编译运行是没太大问题的。至于 armv8 和 armv7 是否能够支持不太确定

**Comment by icyleaf** [comment]
使用最新 `nightly` tag 部署看看？

**Comment by Mabisi** [comment]
> 使用最新 `nightly` tag 部署看看？

已经可以正常运行
